// Display names for strand/topic ids — kept separate from the ids themselves
// so French strands can show their accents even though ids stay plain ASCII.
export const STRAND_LABELS = {
  'reading-comprehension': 'Reading comprehension',
  'language-conventions': 'Language conventions',
  'vocabulary-figurative': 'Vocabulary & figurative language',
  'verbal-reasoning': 'Verbal reasoning',
  'comprehension-lecture': 'Compréhension de lecture',
  grammaire: 'Grammaire',
  conjugaison: 'Conjugaison',
  'orthographe-homophones': 'Orthographe & homophones',
  vocabulaire: 'Vocabulaire',
  'numbers-operations': 'Numbers & operations',
  'fractions-percent': 'Fractions & percent',
  geometry: 'Geometry',
  measurement: 'Measurement',
  'stats-probability': 'Stats & probability',
  'problem-solving-patterns': 'Problem solving & patterns',
  'place-value': 'Place value',
  'place-value-reasoning': 'Place value reasoning',
  'expanded-form': 'Expanded form',
  'compare-expressions': 'Comparing numbers',
  'multi-digit-arithmetic': 'Add, subtract, multiply, divide',
  rounding: 'Rounding',
  'number-properties': 'Prime, composite & square numbers',
  'prime-factorization': 'Prime factors',
  multiples: 'Multiples',
  'equivalent-expressions': 'Equivalent expressions',
  'order-of-operations': 'Order of operations',
  'factors-multiples': 'Factors',
  'negative-numbers': 'Negative numbers',
  'decimal-number-line': 'Decimals on a number line',
  'equivalent-fractions': 'Equivalent fractions',
  'compare-fractions': 'Comparing fractions',
  'not-equivalent': 'Fractions & decimals: odd one out',
  'add-subtract-fractions': 'Adding & subtracting fractions',
  'fraction-of-quantity': 'Fraction of a quantity',
  'fraction-decimal-percent': 'Fractions, decimals & percent',
  'percent-of-number': 'Percent of a number',
  'angle-types': 'Types of angles',
  coordinates: 'Coordinate plane',
  'reflection-translation': 'Reflections & translations',
  'solids-properties': '3D solids & nets',
  polygons: 'Polygons',
  'perimeter-area': 'Perimeter & area',
  'grid-area-perimeter': 'Area & perimeter on a grid',
  'volume-prisms': 'Volume of prisms',
  'volume-cubes': 'Volume with unit cubes',
  'unit-conversion': 'Unit conversion',
  'decimetre-rectangle': 'Rectangles in decimetres',
  'elapsed-time': 'Time',
  'mean-average': 'Mean (average)',
  'reading-graphs': 'Reading graphs',
  'median-mode-range': 'Median, mode & range',
  'temperature-table': 'Reading a table',
  'simple-probability': 'Probability',
  'spinner-likelihood': 'Spinners & likelihood',
  'number-sequences': 'Number patterns',
  'word-problems-gen': 'Word problems',
}

export function strandLabel(strand) {
  return STRAND_LABELS[strand] || strand.replace(/-/g, ' ')
}
