export const cards = [
  { onePoint: "Quiz", threePoint: "Pop Quiz", deck: 'base' },
  { onePoint: "Fence", threePoint: "Electric fence", deck: 'base' },
  { onePoint: "Doughnut", threePoint: "Glazed Doughnut", deck: 'base' },
  { onePoint: "Funeral", threePoint: "Funeral Horne", deck: 'base' },
  { onePoint: "Blood", threePoint: "Blood Bank", deck: 'base' },
  { onePoint: "Side", threePoint: "Bedside", deck: 'base' },
  { onePoint: "Window", threePoint: "Window Shopping", deck: 'base' },
  { onePoint: "Toy", threePoint: "Toy Poodle", deck: 'base' },
  { onePoint: "Gold", threePoint: "Gold Rush", deck: 'base' },
  { onePoint: "Fruit", threePoint: "Fruitcake", deck: 'base' },
  { onePoint: "Love", threePoint: "Love Letter", deck: 'base' },
  { onePoint: "Taco", threePoint: "Taco Salad", deck: 'base' },
  { onePoint: "Wash", threePoint: "Dishwasher", deck: 'base' },
  { onePoint: "Whale", threePoint: "Beached Whale", deck: 'base' },
  { onePoint: "Happy", threePoint: "Happy Hour", deck: 'base' },
  { onePoint: "Mind", threePoint: "Mind Reader", deck: 'base' },
  { onePoint: "Wedding", threePoint: "Wedding Ring", deck: 'base' },
  { onePoint: "Tongue", threePoint: "Tongue-tied", deck: 'base' },
  { onePoint: "Tape", threePoint: "Tape Recorder", deck: 'base' },
  { onePoint: "Walk", threePoint: "Sleep Walking", deck: 'base' },
  { onePoint: "Empty", threePoint: "Empty Calories", deck: 'base' },
  { onePoint: "Bank", threePoint: "Bank Robber", deck: 'base' },
  { onePoint: "Sweat", threePoint: "Cold Sweat", deck: 'base' },
  { onePoint: "Newspaper", threePoint: "Newspaper Headline", deck: 'base' },
  { onePoint: "Hat", threePoint: "Top Hat", deck: 'base' },
  { onePoint: "Skin", threePoint: "Snake Skin", deck: 'base' },
  { onePoint: "Fall", threePoint: "Trust Fall", deck: 'base' },
  { onePoint: "Email", threePoint: "Email Scam", deck: 'base' },
  { onePoint: "Sink", threePoint: "Sinkhole", deck: 'base' },
  { onePoint: "Suit", threePoint: "Bathing Suit", deck: 'base' },
  { onePoint: "Hair", threePoint: "Bad Hair Day", deck: 'base' },
  { onePoint: "Wife", threePoint: "Trophy Wife", deck: 'base' },
  { onePoint: "Frog", threePoint: "Leap Frog", deck: 'base' },
  { onePoint: "Refrigerator", threePoint: "Refrigerator Sale", deck: 'base' },
  { onePoint: "Voice", threePoint: "Voicemail", deck: 'base' },
  { onePoint: "Split", threePoint: "Split Ends", deck: 'base' },
  { onePoint: "Toilet", threePoint: "Toilet Paper", deck: 'base' },
  { onePoint: "Family", threePoint: "Crime family", deck: 'base' },
  { onePoint: "Tall", threePoint: "Tall Order", deck: 'base' },
  { onePoint: "Teacher", threePoint: "Substitute Teacher", deck: 'base' },
  { onePoint: "Talk", threePoint: "Talk Radio", deck: 'base' },
  { onePoint: "Sun", threePoint: "Sunburn", deck: 'base' },
  { onePoint: "Spoon", threePoint: "Measuring Spoon", deck: 'base' },
  { onePoint: "Fry", threePoint: "French Fry", deck: 'base' },
  { onePoint: "Surgery", threePoint: "Plastic Surgery", deck: 'base' },
  { onePoint: "Ghost", threePoint: "Ghost Town", deck: 'base' },
  { onePoint: "Golf", threePoint: "Mini Golf", deck: 'base' },
  { onePoint: "Taste", threePoint: "Taste Buds", deck: 'base' },
  { onePoint: "Glove", threePoint: "Boxing Glove", deck: 'base' },
  { onePoint: "Handle", threePoint: "Handlebar", deck: 'base' },
  { onePoint: "Friend", threePoint: "Best Friends", deck: 'base' },
  { onePoint: "Elephant", threePoint: "Elephant Ear", deck: 'base' },
  { onePoint: "Hand", threePoint: "Handshake", deck: 'base' },
  { onePoint: "Stone", threePoint: "Stonehenge", deck: 'base' },
  { onePoint: "Question", threePoint: "Trick Question", deck: 'base' },
  { onePoint: "Green", threePoint: "Green Thumb", deck: 'base' },
  { onePoint: "Vegetable", threePoint: "Vegetable Garden", deck: 'base' },
  { onePoint: "Table", threePoint: "Ping Pong Table", deck: 'base' },
  { onePoint: "Vacation", threePoint: "Paid Vacation", deck: 'base' },
  { onePoint: "Sugar", threePoint: "Brown Sugar", deck: 'base' },
  { onePoint: "Sweater", threePoint: "Sweater Weather", deck: 'base' },
  { onePoint: "Syrup", threePoint: "Maple Syrup", deck: 'base' },
  { onePoint: "Silent", threePoint: "Silent Night", deck: 'base' },
  { onePoint: "Grass", threePoint: "Grass Skirt", deck: 'base' },
  { onePoint: "Sleep", threePoint: "Sleeping Giant", deck: 'base' },
  { onePoint: "Wave", threePoint: "Tidal Wave", deck: 'base' },
  { onePoint: "World", threePoint: "World Map", deck: 'base' },
  { onePoint: "Drum", threePoint: "Drumstick", deck: 'base' },
  { onePoint: "Wall", threePoint: "Wall Street", deck: 'base' },
  { onePoint: "Easy", threePoint: "Speakeasy", deck: 'base' },
  { onePoint: "Ladder", threePoint: "Rope Ladder", deck: 'base' },
  { onePoint: "Globe", threePoint: "Snow Globe", deck: 'base' },
  { onePoint: "Stool", threePoint: "Stool Pigeon", deck: 'base' },
  { onePoint: "Fact", threePoint: "Fact Finder", deck: 'base' },
  { onePoint: "Water", threePoint: "White Water Rafting", deck: 'base' },
  { onePoint: "Farm", threePoint: "Dairy Farm", deck: 'base' },
  { onePoint: "Sword", threePoint: "Sword Fight", deck: 'base' },
  { onePoint: "Fist", threePoint: "Fist Bump", deck: 'base' },
  { onePoint: "Double", threePoint: "Double Trouble", deck: 'base' },
  { onePoint: "Down", threePoint: "Rundown", deck: 'base' },
  { onePoint: "Summer", threePoint: "Summer Vacation", deck: 'base' },
  { onePoint: "Fossil", threePoint: "Fossil Fuel", deck: 'base' },
  { onePoint: "Foot", threePoint: "Bigfoot", deck: 'base' },
  { onePoint: "Gas", threePoint: "Gas Mask", deck: 'base' },
  { onePoint: "Fork", threePoint: "Fork Lift", deck: 'base' },
  { onePoint: "Dry", threePoint: "Dry Ice", deck: 'base' },
  { onePoint: "Egg", threePoint: "Eggnog", deck: 'base' },
  { onePoint: "Scarf", threePoint: "Wool Scarf", deck: 'base' },
  { onePoint: "Dream", threePoint: "Dream Team", deck: 'base' },
  { onePoint: "Earth", threePoint: "Mother Earth", deck: 'base' },
  { onePoint: "Driver", threePoint: "Racecar Driver", deck: 'base' },
  { onePoint: "Stop", threePoint: "Truck Stop", deck: 'base' },
  { onePoint: "Fire", threePoint: "Fire Hydrant", deck: 'base' },
  { onePoint: "Spill", threePoint: "Spilled Milk", deck: 'base' },
  { onePoint: "Tooth", threePoint: "Tooth Fairy", deck: 'base' },
  { onePoint: "Garage", threePoint: "Garage Band", deck: 'base' },
  { onePoint: "Glass", threePoint: "Champagne Glass", deck: 'base' },
  { onePoint: "Drive", threePoint: "Thumb Drive", deck: 'base' },
  { onePoint: "Finger", threePoint: "Fingernail Polish", deck: 'base' },
  { onePoint: "Hamster", threePoint: "Hamster Wheel", deck: 'base' },
  { onePoint: "Track", threePoint: "Tracksuit", deck: 'base' },
  { onePoint: "Trash", threePoint: "Trash Can", deck: 'base' },
  { onePoint: "Lip", threePoint: "Lipstick", deck: 'base' },
  { onePoint: "Hawk", threePoint: "Mohawk", deck: 'base' },
  { onePoint: "House", threePoint: "Roughhouse", deck: 'base' },
  { onePoint: "Five", threePoint: "High Five", deck: 'base' },
  { onePoint: "Tree", threePoint: "Treehouse", deck: 'base' },
  { onePoint: "Spot", threePoint: "Sweet Spot", deck: 'base' },
  { onePoint: "Team", threePoint: "Swim Team", deck: 'base' },
  { onePoint: "Short", threePoint: "Short Circuit", deck: 'base' },
  { onePoint: "Hot", threePoint: "Hot Sauce", deck: 'base' },
  { onePoint: "Stomach", threePoint: "Stomach Cramp", deck: 'base' },
  { onePoint: "Heart", threePoint: "Broken Heart", deck: 'base' },
  { onePoint: "Stamp", threePoint: "Stamp Collection", deck: 'base' },
  { onePoint: "Hungry", threePoint: "Power Hungry", deck: 'base' },
  { onePoint: "Life", threePoint: "Life Sentence", deck: 'base' },
  { onePoint: "Under", threePoint: "Under Pressure", deck: 'base' },
  { onePoint: "Storm", threePoint: "Thunderstorm", deck: 'base' },
  { onePoint: "Gum", threePoint: "Gumball", deck: 'base' },
  { onePoint: "Hunt", threePoint: "Hunting Party", deck: 'base' },
  { onePoint: "Ketchup", threePoint: "Ketchup Packet", deck: 'base' },
  { onePoint: "Trip", threePoint: "Road Trip", deck: 'base' },
  { onePoint: "Zoo", threePoint: "Petting Zoo", deck: 'base' },
  { onePoint: "Head", threePoint: "Bonehead", deck: 'base' },
  { onePoint: "Ice", threePoint: "Ice Cream Sandwich", deck: 'base' },
  { onePoint: "Train", threePoint: "Training Wheels", deck: 'base' },
  { onePoint: "Kill", threePoint: "Roadkill", deck: 'base' },
  { onePoint: "Student", threePoint: "Student Driver", deck: 'base' },
  { onePoint: "Smoke", threePoint: "Smoke Stack", deck: 'base' },
  { onePoint: "Snake", threePoint: "Rattlesnake", deck: 'base' },
  { onePoint: "Shoe", threePoint: "Shoelace", deck: 'base' },
  { onePoint: "Turtle", threePoint: "Turtle Soup", deck: 'base' },
  { onePoint: "Up", threePoint: "Upstairs", deck: 'base' },
  { onePoint: "First", threePoint: "First Lady", deck: 'base' },
  { onePoint: "Kick", threePoint: "Scissor Kick", deck: 'base' },
  { onePoint: "Trap", threePoint: "Tourist Trap", deck: 'base' },
  { onePoint: "Lick", threePoint: "Salt Lick", deck: 'base' },
  { onePoint: "Wolf", threePoint: "Werewolf", deck: 'base' },
  { onePoint: "Army", threePoint: "Army Ant", deck: 'base' },
  { onePoint: "Shrimp", threePoint: "Jumbo Shrimp", deck: 'base' },
  { onePoint: "Skirt", threePoint: "Skirt Steak", deck: 'base' },
  { onePoint: "Lion", threePoint: "Lion Heart", deck: 'base' },
  { onePoint: "Street", threePoint: "Street Sweeper", deck: 'base' },
  { onePoint: "Shower", threePoint: "Cold Shower", deck: 'base' },
  { onePoint: "Socks", threePoint: "Loose Socks", deck: 'base' },
  { onePoint: "Kitchen", threePoint: "Kitchen Sink", deck: 'base' },
  { onePoint: "Zebra", threePoint: "Zebra Stripes", deck: 'base' },
  { onePoint: "Tutor", threePoint: "Math Tutor", deck: 'base' },
  { onePoint: "Hotel", threePoint: "Five Star Hotel", deck: 'base' },
  { onePoint: "Wood", threePoint: "Wooden Teeth", deck: 'base' },
  { onePoint: "Star", threePoint: "Shooting Star", deck: 'base' },
  { onePoint: "Dog", threePoint: "Doghouse", deck: 'base' },
  { onePoint: "Snow", threePoint: "Snowball Fight", deck: 'base' },
  { onePoint: "Jacket", threePoint: "Yellow Jacket", deck: 'base' },
  { onePoint: "Sloppy", threePoint: "Sloppy Joe", deck: 'base' },
  { onePoint: "Toast", threePoint: "Burnt Toast", deck: 'base' },
  { onePoint: "Airport", threePoint: "Airport Security", deck: 'base' },
  { onePoint: "Wheel", threePoint: "Ferris Wheel", deck: 'base' },
  { onePoint: "Fight", threePoint: "Pillow Fight", deck: 'base' },
  { onePoint: "Flower", threePoint: "Flower Power", deck: 'base' },
  { onePoint: "Lemon", threePoint: "Lemon Slice", deck: 'base' },
  { onePoint: "Shell", threePoint: "Seashell", deck: 'base' },
  { onePoint: "Juice", threePoint: "Orange Juice", deck: 'base' },
  { onePoint: "Hip", threePoint: "Hip Hop", deck: 'base' },
  { onePoint: "Stick", threePoint: "Matchstick", deck: 'base' },
  { onePoint: "Soup", threePoint: "Soup Spoon", deck: 'base' },
  { onePoint: "Hospital", threePoint: "Hospital Gown", deck: 'base' },
  { onePoint: "Tiger", threePoint: "Tiger Cub", deck: 'base' },
  { onePoint: "Jar", threePoint: "Tip Jar", deck: 'base' },
  { onePoint: "Strawberry", threePoint: "Strawberry Jam", deck: 'base' },
  { onePoint: "Lap", threePoint: "Laptop", deck: 'base' },
  { onePoint: "Horse", threePoint: "Horseradish", deck: 'base' },
  { onePoint: "White", threePoint: "White Rabbit", deck: 'base' },
  { onePoint: "School", threePoint: "Driving School", deck: 'base' },
  { onePoint: "Fish", threePoint: "Fishing Pole", deck: 'base' },
  { onePoint: "Square", threePoint: "Town Square", deck: 'base' },
  { onePoint: "Light", threePoint: "Stop Light", deck: 'base' },
  { onePoint: "Shark", threePoint: "Hammerhead Shark", deck: 'base' },
  { onePoint: "Knee", threePoint: "Knee Socks", deck: 'base' },
  { onePoint: "Flame", threePoint: "Flamethrower", deck: 'base' },
  { onePoint: "Ten", threePoint: "Perfect Ten", deck: 'base' },
  { onePoint: "High", threePoint: "High School", deck: 'base' },
  { onePoint: "Land", threePoint: "Landscape", deck: 'base' },
  { onePoint: "Fly", threePoint: "Flying Saucer", deck: 'base' },
  { onePoint: "Soft", threePoint: "Soft Pretzel", deck: 'base' },
  { onePoint: "Start", threePoint: "Startup", deck: 'base' },
  { onePoint: "Shirt", threePoint: "Hawaiian Shirt", deck: 'base' },
  { onePoint: "Seven", threePoint: "Seven Deadly Sins", deck: 'base' },
  { onePoint: "Sausage", threePoint: "Breakfast Sausage", deck: 'base' },
  { onePoint: "Home", threePoint: "Homeless", deck: 'base' },
  { onePoint: "Foil", threePoint: "Tin Foil Hat", deck: 'base' },
  { onePoint: "Jeans", threePoint: "Blue Jeans", deck: 'base' },
  { onePoint: "Jelly", threePoint: "Jelly Doughnut", deck: 'base' },
  { onePoint: "Leather", threePoint: "Leather Jacket", deck: 'base' },
  { onePoint: "Secret", threePoint: "Secret Recipe", deck: 'base' },
  { onePoint: "Food", threePoint: "Fast Food", deck: 'base' },
  { onePoint: "Leg", threePoint: "Chicken Leg", deck: 'base' },
  { onePoint: "Thumb", threePoint: "Thumb War", deck: 'base' },
  { onePoint: "Hole", threePoint: "Black Hole", deck: 'base' },
  { onePoint: "Island", threePoint: "Deserted Island", deck: 'base' },
  { onePoint: "Menu", threePoint: "Breakfast Menu", deck: 'base' },
  { onePoint: "Blade", threePoint: "Rollerblade", deck: 'base' },
  { onePoint: "Nap", threePoint: "Catnap", deck: 'base' },
  { onePoint: "Cake", threePoint: "Carrot Cake", deck: 'base' },
  { onePoint: "Barn", threePoint: "Barn Owl", deck: 'base' },
  { onePoint: "Advice", threePoint: "Free Advice", deck: 'base' },
  { onePoint: "Candy", threePoint: "Cotton Candy", deck: 'base' },
  { onePoint: "Crumb", threePoint: "Cookie Crumbs", deck: 'base' },
  { onePoint: "Seat", threePoint: "Ejection Seat", deck: 'base' },
  { onePoint: "Bird", threePoint: "Bird Cage", deck: 'base' },
  { onePoint: "Poop", threePoint: "Poop Scoop", deck: 'base' },
  { onePoint: "Massage", threePoint: "Massage Table", deck: 'base' },
  { onePoint: "Alligator", threePoint: "Alligator Wrestling", deck: 'base' },
  { onePoint: "Radio", threePoint: "Radioactive", deck: 'base' },
  { onePoint: "Sand", threePoint: "Sandstorm", deck: 'base' },
  { onePoint: "Birthday", threePoint: "Surprise Birthday Party", deck: 'base' },
  { onePoint: "Bag", threePoint: "Bagpipes", deck: 'base' },
  { onePoint: "Angel", threePoint: "Snow Angel", deck: 'base' },
  { onePoint: "Bath", threePoint: "Sponge Bath", deck: 'base' },
  { onePoint: "Cone", threePoint: "Waffle Cone", deck: 'base' },
  { onePoint: "Pie", threePoint: "Pie Crust", deck: 'base' },
  { onePoint: "Baby", threePoint: "Babysitter", deck: 'base' },
  { onePoint: "Bite", threePoint: "Spider Bite", deck: 'base' },
  { onePoint: "Movie", threePoint: "Movie Popcorn", deck: 'base' },
  { onePoint: "Pump", threePoint: "Pump Iron", deck: 'base' },
  { onePoint: "Batter", threePoint: "Hey, Batter, Batter!", deck: 'base' },
  { onePoint: "Sack", threePoint: "Hacky Sack", deck: 'base' },
  { onePoint: "Road", threePoint: "Road Rage", deck: 'base' },
  { onePoint: "Puppy", threePoint: "Puppy Party", deck: 'base' },
  { onePoint: "Parade", threePoint: "Parade Float", deck: 'base' },
  { onePoint: "Small", threePoint: "Small Fry", deck: 'base' },
  { onePoint: "Circle", threePoint: "Full Circle", deck: 'base' },
  { onePoint: "Balloon", threePoint: "Water Balloon Fight", deck: 'base' },
  { onePoint: "Bounce", threePoint: "Bounce Back", deck: 'base' },
  { onePoint: "Crash", threePoint: "Wedding Crasher", deck: 'base' },
  { onePoint: "Bar", threePoint: "Salad Bar", deck: 'base' },
  { onePoint: "Close", threePoint: "Close Encounter", deck: 'base' },
  { onePoint: "Castle", threePoint: "Sand Castle", deck: 'base' },
  { onePoint: "Brush", threePoint: "Paintbrush", deck: 'base' },
  { onePoint: "Bug", threePoint: "Lightning Bug", deck: 'base' },
  { onePoint: "Animal", threePoint: "Animal Cracker", deck: 'base' },
  { onePoint: "Ant", threePoint: "Anteater", deck: 'base' },
  { onePoint: "Bone", threePoint: "Funny Bone", deck: 'base' },
  { onePoint: "Clam", threePoint: "Clam Chowder", deck: 'base' },
  { onePoint: "Pumpkin", threePoint: "Pumpkin Patch", deck: 'base' },
  { onePoint: "Apple", threePoint: "Bad Apple", deck: 'base' },
  { onePoint: "Salad", threePoint: "Caesar Salad", deck: 'base' },
  { onePoint: "Camera", threePoint: "Disposable Camera", deck: 'base' },
  { onePoint: "Pickle", threePoint: "Pickle Jar", deck: 'base' },
  { onePoint: "Break", threePoint: "Winter Break", deck: 'base' },
  { onePoint: "Bench", threePoint: "Bench Warmer", deck: 'base' },
  { onePoint: "Cow", threePoint: "Cash Cow", deck: 'base' },
  { onePoint: "Pork", threePoint: "Pork Belly", deck: 'base' },
  { onePoint: "Cut", threePoint: "Short Cut", deck: 'base' },
  { onePoint: "Root", threePoint: "Root Beer", deck: 'base' },
  { onePoint: "Salt", threePoint: "Salted Caramel", deck: 'base' },
  { onePoint: "Pancake", threePoint: "Blueberry Pancake", deck: 'base' },
  { onePoint: "Bucket", threePoint: "Bucket List", deck: 'base' },
  { onePoint: "Boot", threePoint: "Rain Boot", deck: 'base' },
  { onePoint: "Belly", threePoint: "Yellow Belly", deck: 'base' },
  { onePoint: "Roast", threePoint: "Pot Roast", deck: 'base' },
  { onePoint: "Dirt", threePoint: "Dirt Road", deck: 'base' },
  { onePoint: "Butterfly", threePoint: "Butterfly Kiss", deck: 'base' },
  { onePoint: "Potato", threePoint: "Mashed Potatoes", deck: 'base' },
  { onePoint: "Ring", threePoint: "Ring Tone", deck: 'base' },
  { onePoint: "Cart", threePoint: "Shopping Cart", deck: 'base' },
  { onePoint: "Peace", threePoint: "Peacemaker", deck: 'base' },
  { onePoint: "Pull", threePoint: "Pull Up", deck: 'base' },
  { onePoint: "Calendar", threePoint: "Lunar Calendar", deck: 'base' },
  { onePoint: "Monkey", threePoint: "Monkey Business", deck: 'base' },
  { onePoint: "Chocolate", threePoint: "Hot Chocolate", deck: 'base' },
  { onePoint: "Puddle", threePoint: "Puddle Jumper", deck: 'base' },
  { onePoint: "Ride", threePoint: "Rideshare", deck: 'base' },
  { onePoint: "Queen", threePoint: "Queen Bee", deck: 'base' },
  { onePoint: "Rain", threePoint: "Rain Dance", deck: 'base' },
  { onePoint: "Cookie", threePoint: "Fortune Cookie", deck: 'base' },
  { onePoint: "Brother", threePoint: "Twin Brother", deck: 'base' },
  { onePoint: "Brain", threePoint: "Brainwash", deck: 'base' },
  { onePoint: "Battle", threePoint: "Battlefield", deck: 'base' },
  { onePoint: "Moon", threePoint: "Moon", deck: 'base' },
  { onePoint: "Bubble", threePoint: "Bubble Bath", deck: 'base' },
  { onePoint: "Button", threePoint: "Panic Button", deck: 'base' },
  { onePoint: "Boy", threePoint: "Water Boy", deck: 'base' },
  { onePoint: "Candle", threePoint: "Candle Wax", deck: 'base' },
  { onePoint: "Room", threePoint: "Emergency Room", deck: 'base' },
  { onePoint: "Band", threePoint: "Heavy Metal Band", deck: 'base' },
  { onePoint: "North", threePoint: "North Pole", deck: 'base' },
  { onePoint: "Bus", threePoint: "Bus Stop", deck: 'base' },
  { onePoint: "Banana", threePoint: "Banana Split", deck: 'base' },
  { onePoint: "Cup", threePoint: "Sippy Cup", deck: 'base' },
  { onePoint: "Rice", threePoint: "Sticky Rice", deck: 'base' },
  { onePoint: "Butter", threePoint: "Butter Ball", deck: 'base' },
  { onePoint: "Bedroom", threePoint: "Guest Bedroom", deck: 'base' },
  { onePoint: "Popcorn", threePoint: "Microwave Popcorn", deck: 'base' },
  { onePoint: "Popsicle", threePoint: "Popsicle Stick", deck: 'base' },
  { onePoint: "Dad", threePoint: "Dad Joke", deck: 'base' },
  { onePoint: "Bread", threePoint: "Banana Bread", deck: 'base' },
  { onePoint: "Bowling", threePoint: "Bowling Shirt", deck: 'base' },
  { onePoint: "Bee", threePoint: "Bee Sting", deck: 'base' },
  { onePoint: "Rose", threePoint: "Rose Petal", deck: 'base' },
  { onePoint: "Beach", threePoint: "Beach Burn", deck: 'base' },
  { onePoint: "Party", threePoint: "Party Pooper", deck: 'base' },
  { onePoint: "Dance", threePoint: "Belly Dance", deck: 'base' },
  { onePoint: "Burrito", threePoint: "Breakfast Burrito", deck: 'base' },
  { onePoint: "Pink", threePoint: "Pink Panther", deck: 'base' },
  { onePoint: "Chain", threePoint: "Chain Gang", deck: 'base' },
  { onePoint: "Oven", threePoint: "Toaster Oven", deck: 'base' },
  { onePoint: "Park", threePoint: "Public Park", deck: 'base' },
  { onePoint: "Man", threePoint: "Man Cave", deck: 'base' },
  { onePoint: "Lucky", threePoint: "Lucky Charm", deck: 'base' },
  { onePoint: "Dinner", threePoint: "Dinner Roll", deck: 'base' },
  { onePoint: "Date", threePoint: "Blind Date", deck: 'base' },
  { onePoint: "Poison", threePoint: "Poison Ivy", deck: 'base' },
  { onePoint: "Crack", threePoint: "Plumber's Crack", deck: 'base' },
  { onePoint: "Boat", threePoint: "Rowboat", deck: 'base' },
  { onePoint: "Pet", threePoint: "Pet Rock", deck: 'base' },
  { onePoint: "Cover", threePoint: "Undercover", deck: 'base' },
  { onePoint: "Nest", threePoint: "Nest Egg", deck: 'base' },
  { onePoint: "Diamond", threePoint: "Baseball Diamond", deck: 'base' },
  { onePoint: "Dark", threePoint: "Dark Horse", deck: 'base' },
  { onePoint: "Crab", threePoint: "Crab Cakes", deck: 'base' },
  { onePoint: "Magic", threePoint: "Magic Carpet Ride", deck: 'base' },
  { onePoint: "Carrot", threePoint: "Baby Carrot", deck: 'base' },
  { onePoint: "Penny", threePoint: "Lucky Penny", deck: 'base' },
  { onePoint: "Coal", threePoint: "Coal Miner", deck: 'base' },
  { onePoint: "Market", threePoint: "Stock Market", deck: 'base' },
  { onePoint: "Cry", threePoint: "Cry Baby", deck: 'base' },
  { onePoint: "Long", threePoint: "Long Jump", deck: 'base' },
  { onePoint: "Day", threePoint: "Daylight", deck: 'base' },
  { onePoint: "Ninja", threePoint: "Silent Ninja", deck: 'base' },
  { onePoint: "Marriage", threePoint: "Marriage License", deck: 'base' },
  { onePoint: "Macaroni", threePoint: "Elbow Macaroni", deck: 'base' },
  { onePoint: "Nail", threePoint: "Nail-Biter", deck: 'base' },
  { onePoint: "Mobile", threePoint: "Mobile Home", deck: 'base' },
  { onePoint: "Death", threePoint: "Death Wish", deck: 'base' },
  { onePoint: "Lunch", threePoint: "Lunch Lady", deck: 'base' },
  { onePoint: "Door", threePoint: "Door Knob", deck: 'base' },
  { onePoint: "Dirty", threePoint: "Dirty Laundry", deck: 'base' },
  { onePoint: "Crayon", threePoint: "Crayon Box", deck: 'base' },
  { onePoint: "Phone", threePoint: "Cell Phone", deck: 'base' },
  { onePoint: "Meat", threePoint: "Meat Eater", deck: 'base' },
  { onePoint: "Money", threePoint: "Money Hungry", deck: 'base' },
  { onePoint: "Brick", threePoint: "Brick Layer", deck: 'base' },
  { onePoint: "Computer", threePoint: "Super Computer", deck: 'base' },
  { onePoint: "Bride", threePoint: "Bridezilla", deck: 'base' },
  { onePoint: "Medicine", threePoint: "Cough Medicine", deck: 'base' },
  { onePoint: "Milk", threePoint: "Chocolate Milk", deck: 'base' },
  { onePoint: "Doctor", threePoint: "Foot Doctor", deck: 'base' },
  { onePoint: "Belt", threePoint: "Belt Loop", deck: 'base' },
  { onePoint: "Break", threePoint: "Winter Break", deck: 'base' },
  { onePoint: "Piano", threePoint: "Dueling Pianos", deck: 'base' },
  { onePoint: "Bottle", threePoint: "Bottle Rocket", deck: 'base' },
  { onePoint: "Pool", threePoint: "Pool Noodle", deck: 'base' },
  { onePoint: "Nurse", threePoint: "Night Nurse", deck: 'base' },
  { onePoint: "Mouth", threePoint: "Big Mouth", deck: 'base' },
  { onePoint: "Mate", threePoint: "Checkmate", deck: 'base' },
  { onePoint: "Chef", threePoint: "Pastry Chef", deck: 'base' },
  { onePoint: "Nose", threePoint: "Nose Job", deck: 'base' },
  { onePoint: "Note", threePoint: "Sticky Note", deck: 'base' },
  { onePoint: "Pail", threePoint: "Lunch Pail", deck: 'base' },
  { onePoint: "Pants", threePoint: "Cargo Pants", deck: 'base' },
  { onePoint: "Guitar", threePoint: "Acoustic Guitar", deck: 'base' },
  { onePoint: "Pan", threePoint: "Panhandle", deck: 'base' },
  { onePoint: "Pole", threePoint: "Pole Vault", deck: 'base' },
  { onePoint: "Pack", threePoint: "Six Pack", deck: 'base' },
  { onePoint: "Bowl", threePoint: "Goldfish Bowl", deck: 'base' },
  { onePoint: "Bacon", threePoint: "Bacon, Bacon, Bacon!", deck: 'base' },
  { onePoint: "Old", threePoint: "Old Man", deck: 'base' },
  { onePoint: "Roll", threePoint: "Rock 'n' Roll", deck: 'base' },
  { onePoint: "Coffee", threePoint: "Instant Coffee", deck: 'base' },
  { onePoint: "Morning", threePoint: "Morning Person", deck: 'base' },
  { onePoint: "Cheese", threePoint: "Grilled Cheese", deck: 'base' },
  { onePoint: "Police", threePoint: "Police Lineup", deck: 'base' },
  { onePoint: "Neck", threePoint: "Necktie", deck: 'base' },
  { onePoint: "Blanket", threePoint: "Wet Blanket", deck: 'base' },
  { onePoint: "Chicken", threePoint: "Chicken Nugget", deck: 'base' },
  { onePoint: "Pizza", threePoint: "Pizza Pie", deck: 'base' },
  { onePoint: "Rags", threePoint: "Rags to Riches", deck: 'base' },
  { onePoint: "Clown", threePoint: "Clown Shoes", deck: 'base' },
  { onePoint: "Olympics", threePoint: "Summer Olympics", deck: 'base' },
  { onePoint: "Plate", threePoint: "Paper Plate", deck: 'base' },
  { onePoint: "Dead", threePoint: "Dead Weight", deck: 'base' },
  { onePoint: "Poker", threePoint: "Poker Chip", deck: 'base' },
  { onePoint: "Name", threePoint: "Nickname", deck: 'base' },
  { onePoint: "Boil", threePoint: "Hard-Boiled Egg", deck: 'base' },
  { onePoint: "Pitch", threePoint: "Pitchfork", deck: 'base' },
  { onePoint: "Oil", threePoint: "Oil Spill", deck: 'base' },
  { onePoint: "Muscle", threePoint: "Musclehead", deck: 'base' },
  { onePoint: "Pillow", threePoint: "Pillow Talk", deck: 'base' },
  { onePoint: "Mountain", threePoint: "Mountain Man", deck: 'base' },
  { onePoint: "Bun", threePoint: "Cinnamon Bun", deck: 'base' },
  { onePoint: "Picnic", threePoint: "Picnic Basket", deck: 'base' },
  { onePoint: "Chair", threePoint: "Rocking Chair", deck: 'base' },
  { onePoint: "Paper", threePoint: "Paper Cut", deck: 'base' },
  { onePoint: "Noise", threePoint: "Noise Pollution", deck: 'base' },
  { onePoint: "Photo", threePoint: "Photo Finish", deck: 'base' },
  { onePoint: "Bathroom", threePoint: "Public Bathroom", deck: 'base' },
  { onePoint: "Watch", threePoint: "Pocket Watch", deck: 'base' },
  { onePoint: "Club", threePoint: "Club Sandwich", deck: 'base' },
  { onePoint: "Private", threePoint: "Private Detective", deck: 'base' },
  { onePoint: "Stretch", threePoint: "Stretchy Pants", deck: 'expansion' },
  { onePoint: "Stork", threePoint: "Stork Baby", deck: 'expansion' },
  { onePoint: "Sticker", threePoint: "Bumper Sticker", deck: 'expansion' },
  { onePoint: "Steer", threePoint: "Steering Wheel", deck: 'expansion' },
  { onePoint: "Steel", threePoint: "Steel Wool", deck: 'expansion' },
  { onePoint: "Steam", threePoint: "Steamboat", deck: 'expansion' },
  { onePoint: "Steal", threePoint: "Steal Your Heart", deck: 'expansion' },
  { onePoint: "Station", threePoint: "Gas Station", deck: 'expansion' },
  { onePoint: "Staple", threePoint: "Staple Gun", deck: 'expansion' },
  { onePoint: "Stain", threePoint: "Stained Glass", deck: 'expansion' },
  { onePoint: "Stack", threePoint: "Shortstack", deck: 'expansion' },
  { onePoint: "Squirrel", threePoint: "Gray Squirrel", deck: 'expansion' },
  { onePoint: "Squid", threePoint: "Squid Ink", deck: 'expansion' },
  { onePoint: "Style", threePoint: "Lifestyle", deck: 'expansion' },
  { onePoint: "Surfing", threePoint: "Web Surfing", deck: 'expansion' },
  { onePoint: "Swamp", threePoint: "Murky Swamp", deck: 'expansion' },
  { onePoint: "Swat", threePoint: "Flyswatter", deck: 'expansion' },
  { onePoint: "Sweep", threePoint: "Chimmney Sweep", deck: 'expansion' },
  { onePoint: "Sweet", threePoint: "Sweet Tooth", deck: 'expansion' },
  { onePoint: "Swing", threePoint: "Mood Swing", deck: 'expansion' },
  { onePoint: "Swirl", threePoint: "Ice Cream Swirl", deck: 'expansion' },
  { onePoint: "System", threePoint: "Solar System", deck: 'expansion' },
  { onePoint: "Tackle", threePoint: "Football Tackle", deck: 'expansion' },
  { onePoint: "Taffy", threePoint: "Saltwater Taffy", deck: 'expansion' },
  { onePoint: "Squeeze", threePoint: "Main Squeeze", deck: 'expansion' },
  { onePoint: "Thunder", threePoint: "Thundercloud", deck: 'expansion' },
  { onePoint: "Thought", threePoint: "Afterthought", deck: 'expansion' },
  { onePoint: "Thigh", threePoint: "Thigh Highs", deck: 'expansion' },
  { onePoint: "Tennis", threePoint: "Tennis Racket", deck: 'expansion' },
  { onePoint: "Temple", threePoint: "Temple Shrine", deck: 'expansion' },
  { onePoint: "Tattoo", threePoint: "Full Sleeve Tattoo", deck: 'expansion' },
  { onePoint: "Task", threePoint: "Simple Task", deck: 'expansion' },
  { onePoint: "Target", threePoint: "Target Practice", deck: 'expansion' },
  { onePoint: "Tan", threePoint: "Suntan", deck: 'expansion' },
  { onePoint: "Tambourine", threePoint: "Tambourine Man", deck: 'expansion' },
  { onePoint: "Take", threePoint: "Hot Take", deck: 'expansion' },
  { onePoint: "Squeak", threePoint: "Squeaky Toy", deck: 'expansion' },
  { onePoint: "Slip", threePoint: "Slipknot", deck: 'expansion' },
  { onePoint: "Tights", threePoint: "Sheer Tights", deck: 'expansion' },
  { onePoint: "Tinfoil", threePoint: "Tinfoil Hat", deck: 'expansion' },
  { onePoint: "Tip", threePoint: "Pencil Tip", deck: 'expansion' },
  { onePoint: "Tired", threePoint: "Tired Eyes", deck: 'expansion' },
  { onePoint: "Toad", threePoint: "Toadstool", deck: 'expansion' },
  { onePoint: "Today", threePoint: "Today's News", deck: 'expansion' },
  { onePoint: "Toe", threePoint: "Tic-Tac-Toe", deck: 'expansion' },
  { onePoint: "Tofu", threePoint: "Firm Tofu", deck: 'expansion' },
  { onePoint: "Topic", threePoint: "Hot Topic", deck: 'expansion' },
  { onePoint: "Torch", threePoint: "Blowtorch", deck: 'expansion' },
  { onePoint: "Sprout", threePoint: "Bean Sprout", deck: 'expansion' },
  { onePoint: "Slipper", threePoint: "Fuzzy Slippers", deck: 'expansion' },
  { onePoint: "Truth", threePoint: "Whole Truth", deck: 'expansion' },
  { onePoint: "Trend", threePoint: "Trendsetter", deck: 'expansion' },
  { onePoint: "Trainer", threePoint: "Personal Trainer", deck: 'expansion' },
  { onePoint: "Traffic", threePoint: "Traffic Cone", deck: 'expansion' },
  { onePoint: "Tradition", threePoint: "Family Tradition", deck: 'expansion' },
  { onePoint: "Trade", threePoint: "Fair Trade", deck: 'expansion' },
  { onePoint: "Tough", threePoint: "Tough Cookie", deck: 'expansion' },
  { onePoint: "Tot", threePoint: "Tater Tot", deck: 'expansion' },
  { onePoint: "Tortoise", threePoint: "Giant Tortoise", deck: 'expansion' },
  { onePoint: "Tornado", threePoint: "Tornado Warning", deck: 'expansion' },
  { onePoint: "Splash", threePoint: "Splish-Splash", deck: 'expansion' },
  { onePoint: "Slope", threePoint: "Steep Slope", deck: 'expansion' },
  { onePoint: "Tuna", threePoint: "Tuna Salad", deck: 'expansion' },
  { onePoint: "Turkey", threePoint: "Turkey Sandwich", deck: 'expansion' },
  { onePoint: "Turn", threePoint: "Turntable", deck: 'expansion' },
  { onePoint: "Tutu", threePoint: "Pancake Tutu", deck: 'expansion' },
  { onePoint: "Uniform", threePoint: "School Uniform", deck: 'expansion' },
  { onePoint: "Union", threePoint: "Union Organizer", deck: 'expansion' },
  { onePoint: "Vacuum", threePoint: "Vacuum Cleaner", deck: 'expansion' },
  { onePoint: "Veil", threePoint: "Wedding Veil", deck: 'expansion' },
  { onePoint: "Venom", threePoint: "Snake Venom", deck: 'expansion' },
  { onePoint: "Vest", threePoint: "Life Vest", deck: 'expansion' },
  { onePoint: "Spin", threePoint: "Spin Cycle", deck: 'expansion' },
  { onePoint: "Sloth", threePoint: "Three-Toed Sloth", deck: 'expansion' },
  { onePoint: "Wig", threePoint: "Wig Cap", deck: 'expansion' },
  { onePoint: "Wide", threePoint: "Wide-Eyed", deck: 'expansion' },
  { onePoint: "Whisper", threePoint: "Dog Whisperer", deck: 'expansion' },
  { onePoint: "Weekend", threePoint: "Weekend Plans", deck: 'expansion' },
  { onePoint: "Walrus", threePoint: "Walrus Tusk", deck: 'expansion' },
  { onePoint: "Wait", threePoint: "Patiently Waiting", deck: 'expansion' },
  { onePoint: "Wagon", threePoint: "Covered Wagon", deck: 'expansion' },
  { onePoint: "Waffle", threePoint: "Waffle Iron", deck: 'expansion' },
  { onePoint: "Voyage", threePoint: "Long Voyage", deck: 'expansion' },
  { onePoint: "Vine", threePoint: "Jungle Vine", deck: 'expansion' },
  { onePoint: "Spike", threePoint: "Volleyball Spike", deck: 'expansion' },
  { onePoint: "Snooze", threePoint: "Snooze Button", deck: 'expansion' },
  { onePoint: "Zipper", threePoint: "Zipper Pull", deck: 'expansion' },
  { onePoint: "Yarn", threePoint: "Yarn Bowl", deck: 'expansion' },
  { onePoint: "Writer", threePoint: "Writer's Block", deck: 'expansion' },
  { onePoint: "Wrinkle", threePoint: "Shirt Wrinkle", deck: 'expansion' },
  { onePoint: "Wrestler", threePoint: "Sumo Wrestler", deck: 'expansion' },
  { onePoint: "Wrench", threePoint: "Crescent Wrench", deck: 'expansion' },
  { onePoint: "Wrap", threePoint: "Wrap It Up", deck: 'expansion' },
  { onePoint: "Wisdom", threePoint: "Wisdom Teeth", deck: 'expansion' },
  { onePoint: "Wire", threePoint: "Barbed Wire", deck: 'expansion' },
  { onePoint: "Wink", threePoint: "Wink Emoji", deck: 'expansion' },
  { onePoint: "Spider", threePoint: "Spiderweb", deck: 'expansion' },
  { onePoint: "Soccer", threePoint: "Soccer Match", deck: 'expansion' },
  { onePoint: "Spear", threePoint: "Spearfishing", deck: 'expansion' },
  { onePoint: "Sound", threePoint: "Sound Effect", deck: 'expansion' },
  { onePoint: "Shout", threePoint: "Shout-Out", deck: 'expansion' },
  { onePoint: "Show", threePoint: "Showstopper", deck: 'expansion' },
  { onePoint: "Shut", threePoint: "Shut Up", deck: 'expansion' },
  { onePoint: "Sick", threePoint: "Worried Sick", deck: 'expansion' },
  { onePoint: "Sign", threePoint: "Neon Sign", deck: 'expansion' },
  { onePoint: "Sit", threePoint: "Sit Down", deck: 'expansion' },
  { onePoint: "Skate", threePoint: "Skate Rink", deck: 'expansion' },
  { onePoint: "Skill", threePoint: "Skill Set", deck: 'expansion' },
  { onePoint: "Skip", threePoint: "Skip Rope", deck: 'expansion' },
  { onePoint: "Sleeve", threePoint: "Long Sleeve", deck: 'expansion' },
  { onePoint: "Sewer", threePoint: "Sewer Drain", deck: 'expansion' },
  { onePoint: "Shade", threePoint: "Lamp Shade", deck: 'expansion' },
  { onePoint: "Shadow", threePoint: "Shadow Puppets", deck: 'expansion' },
  { onePoint: "Shampoo", threePoint: "Shampoo Bottle", deck: 'expansion' },
  { onePoint: "Sheet", threePoint: "Silk Sheet", deck: 'expansion' },
  { onePoint: "Shepherd", threePoint: "Shepherd Dog", deck: 'expansion' },
  { onePoint: "Shine", threePoint: "Sunshine", deck: 'expansion' },
  { onePoint: "Shock", threePoint: "Culture Shock", deck: 'expansion' },
  { onePoint: "Shore", threePoint: "Shoreline", deck: 'expansion' },
  { onePoint: "Shoulder", threePoint: "Shoulder Blade", deck: 'expansion' },
  { onePoint: "Scratch", threePoint: "Scratch Pad", deck: 'expansion' },
  { onePoint: "Screwdriver", threePoint: "Flat-Head Screwdriver", deck: 'expansion' },
  { onePoint: "Search", threePoint: "Soul Searching", deck: 'expansion' },
  { onePoint: "Seaweed", threePoint: "Seaweed Chips", deck: 'expansion' },
  { onePoint: "Seed", threePoint: "Bird Seed", deck: 'expansion' },
  { onePoint: "Seek", threePoint: "Hide-and-Seek", deck: 'expansion' },
  { onePoint: "Send", threePoint: "Send Help", deck: 'expansion' },
  { onePoint: "Sense", threePoint: "Sixth Sense", deck: 'expansion' },
  { onePoint: "Separate", threePoint: "Separate Checks", deck: 'expansion' },
  { onePoint: "Set", threePoint: "Setup", deck: 'expansion' },
  { onePoint: "Rubber", threePoint: "Rubber Stamp", deck: 'expansion' },
  { onePoint: "Rude", threePoint: "Rude Awakening", deck: 'expansion' },
  { onePoint: "Run", threePoint: "Home Run", deck: 'expansion' },
  { onePoint: "Sad", threePoint: "Sad Face", deck: 'expansion' },
  { onePoint: "Sauce", threePoint: "Special Sauce", deck: 'expansion' },
  { onePoint: "Scale", threePoint: "Bathroom Scale", deck: 'expansion' },
  { onePoint: "Scalpel", threePoint: "Scalpel Knife", deck: 'expansion' },
  { onePoint: "Scan", threePoint: "PET Scan", deck: 'expansion' },
  { onePoint: "Scary", threePoint: "Scary Story", deck: 'expansion' },
  { onePoint: "Score", threePoint: "High Score", deck: 'expansion' },
  { onePoint: "Rehersal", threePoint: "Music Rehersal", deck: 'expansion' },
  { onePoint: "Reject", threePoint: "Rejection Letter", deck: 'expansion' },
  { onePoint: "Respect", threePoint: "Pay Respect", deck: 'expansion' },
  { onePoint: "Rhino", threePoint: "White Rhino", deck: 'expansion' },
  { onePoint: "Ripple", threePoint: "Ripple Effect", deck: 'expansion' },
  { onePoint: "Rise", threePoint: "High-Rise", deck: 'expansion' },
  { onePoint: "River", threePoint: "Lazy River", deck: 'expansion' },
  { onePoint: "Roar", threePoint: "Engine Roar", deck: 'expansion' },
  { onePoint: "Rocket", threePoint: "Rocket Launcher", deck: 'expansion' },
  { onePoint: "Rod", threePoint: "Fishing Rod", deck: 'expansion' },
  { onePoint: "Proper", threePoint: "Proper Posture", deck: 'expansion' },
  { onePoint: "Proposal", threePoint: "Marriage Proposal", deck: 'expansion' },
  { onePoint: "Public", threePoint: "Public School", deck: 'expansion' },
  { onePoint: "Push", threePoint: "Push-Up", deck: 'expansion' },
  { onePoint: "Visit", threePoint: "Surprise Visit", deck: 'expansion' },
  { onePoint: "Quarter", threePoint: "Quarterback", deck: 'expansion' },
  { onePoint: "Rabbit", threePoint: "Rabbit Burrow", deck: 'expansion' },
  { onePoint: "Raffle", threePoint: "Giveaway Raffle", deck: 'expansion' },
  { onePoint: "Rebel", threePoint: "Rebel Leader", deck: 'expansion' },
  { onePoint: "Reflection", threePoint: "Self-Reflection", deck: 'expansion' },
  { onePoint: "Plunger", threePoint: "Toilet Plunger", deck: 'expansion' },
  { onePoint: "Pond", threePoint: "Pond Lily", deck: 'expansion' },
  { onePoint: "Pop", threePoint: "Lollipop", deck: 'expansion' },
  { onePoint: "Pot", threePoint: "Potluck", deck: 'expansion' },
  { onePoint: "Potion", threePoint: "Magic Potion", deck: 'expansion' },
  { onePoint: "Pray", threePoint: "Praying Mantis", deck: 'expansion' },
  { onePoint: "President", threePoint: "Club President", deck: 'expansion' },
  { onePoint: "Price", threePoint: "Half Price", deck: 'expansion' },
  { onePoint: "Priority", threePoint: "Low Priority", deck: 'expansion' },
  { onePoint: "Promise", threePoint: "Pinky Promise", deck: 'expansion' },
  { onePoint: "Pepper", threePoint: "Ghost Pepper", deck: 'expansion' },
  { onePoint: "Permit", threePoint: "Driving Permit", deck: 'expansion' },
  { onePoint: "Pick", threePoint: "Pick Me!", deck: 'expansion' },
  { onePoint: "Piece", threePoint: "Piece of Cake", deck: 'expansion' },
  { onePoint: "Pilot", threePoint: "Autopilot", deck: 'expansion' },
  { onePoint: "Pinch", threePoint: "Penny Pincher", deck: 'expansion' },
  { onePoint: "Pipe", threePoint: "Pipe Down", deck: 'expansion' },
  { onePoint: "Plan", threePoint: "Perfect Plan", deck: 'expansion' },
  { onePoint: "Plank", threePoint: "Walk the Plank", deck: 'expansion' },
  { onePoint: "Pliers", threePoint: "Needle Nose Pliers", deck: 'expansion' },
  { onePoint: "Parrot", threePoint: "Talking Parrot", deck: 'expansion' },
  { onePoint: "Partner", threePoint: "Partner in Crime", deck: 'expansion' },
  { onePoint: "Pass", threePoint: "Passport", deck: 'expansion' },
  { onePoint: "Pasture", threePoint: "Cow Pasture", deck: 'expansion' },
  { onePoint: "Pawn", threePoint: "Chess Pawn", deck: 'expansion' },
  { onePoint: "Peacock", threePoint: "Peacock Feather", deck: 'expansion' },
  { onePoint: "Pearl", threePoint: "Pearl Earring", deck: 'expansion' },
  { onePoint: "Peas", threePoint: "Mushy Peas", deck: 'expansion' },
  { onePoint: "Penguin", threePoint: "Emperor Penguin", deck: 'expansion' },
  { onePoint: "People", threePoint: "People Person", deck: 'expansion' },
  { onePoint: "Ostrich", threePoint: "Ostrich Egg", deck: 'expansion' },
  { onePoint: "Otter", threePoint: "Sea Otter", deck: 'expansion' },
  { onePoint: "Outline", threePoint: "Chalk Outline", deck: 'expansion' },
  { onePoint: "Owl", threePoint: "Snowy Owl", deck: 'expansion' },
  { onePoint: "Ox", threePoint: "Musk Ox", deck: 'expansion' },
  { onePoint: "Pace", threePoint: "Pacemaker", deck: 'expansion' },
  { onePoint: "Paint", threePoint: "Wall Paint", deck: 'expansion' },
  { onePoint: "Pale", threePoint: "Pale Moonlight", deck: 'expansion' },
  { onePoint: "Palm", threePoint: "Palm Tree", deck: 'expansion' },
  { onePoint: "Panda", threePoint: "Trash Panda", deck: 'expansion' },
  { onePoint: "Grumble", threePoint: "Stomach Grumble", deck: 'expansion' },
  { onePoint: "Growl", threePoint: "Growler", deck: 'expansion' },
  { onePoint: "Grow", threePoint: "Growing Pains", deck: 'expansion' },
  { onePoint: "Ground", threePoint: "Groundhog", deck: 'expansion' },
  { onePoint: "Gross", threePoint: "Gross Out", deck: 'expansion' },
  { onePoint: "Grin", threePoint: "Toothy Grin", deck: 'expansion' },
  { onePoint: "Grim", threePoint: "Grim Reaper", deck: 'expansion' },
  { onePoint: "Grill", threePoint: "Grill Pan", deck: 'expansion' },
  { onePoint: "Gravity", threePoint: "Zero Gravity", deck: 'expansion' },
  { onePoint: "Grab", threePoint: "Grab Bag", deck: 'expansion' },
  { onePoint: "Human", threePoint: "Human Nature", deck: 'expansion' },
  { onePoint: "Hum", threePoint: "Hummingbird", deck: 'expansion' },
  { onePoint: "Hour", threePoint: "Amateur Hour", deck: 'expansion' },
  { onePoint: "Hop", threePoint: "Hopscotch", deck: 'expansion' },
  { onePoint: "Holler", threePoint: "Holler Back", deck: 'expansion' },
  { onePoint: "Hike", threePoint: "Day Hike", deck: 'expansion' },
  { onePoint: "Helmet", threePoint: "Bike Helmet", deck: 'expansion' },
  { onePoint: "Heel", threePoint: "High Heels", deck: 'expansion' },
  { onePoint: "Haunt", threePoint: "Haunted House", deck: 'expansion' },
  { onePoint: "Haul", threePoint: "Overhaul", deck: 'expansion' },
  { onePoint: "Knowledge", threePoint: "Forbidden Knowledge", deck: 'expansion' },
  { onePoint: "Keep", threePoint: "Castle Keep", deck: 'expansion' },
  { onePoint: "Kangaroo", threePoint: "Kangaroo Pouch", deck: 'expansion' },
  { onePoint: "Jungle", threePoint: "Concrete Jungle", deck: 'expansion' },
  { onePoint: "Join", threePoint: "Join the Club", deck: 'expansion' },
  { onePoint: "Jam", threePoint: "Jam-Packed", deck: 'expansion' },
  { onePoint: "Itch", threePoint: "Itchy Feet", deck: 'expansion' },
  { onePoint: "Invitation", threePoint: "Party Invitation", deck: 'expansion' },
  { onePoint: "Insult", threePoint: "Hurl Insults", deck: 'expansion' },
  { onePoint: "Inspector", threePoint: "Home Inspector", deck: 'expansion' },
  { onePoint: "Opposite", threePoint: "Opposites Attract", deck: 'expansion' },
  { onePoint: "Onion", threePoint: "Onion Rings", deck: 'expansion' },
  { onePoint: "Omelet", threePoint: "Vegetable Omelet", deck: 'expansion' },
  { onePoint: "Odd", threePoint: "Odd Bird", deck: 'expansion' },
  { onePoint: "Oatmeal", threePoint: "Instant Oatmeal", deck: 'expansion' },
  { onePoint: "Nod", threePoint: "Nod Off", deck: 'expansion' },
  { onePoint: "Net", threePoint: "Fishnet", deck: 'expansion' },
  { onePoint: "Nerve", threePoint: "Last Nerve", deck: 'expansion' },
  { onePoint: "Neighbor", threePoint: "Nosey Neighbor", deck: 'expansion' },
  { onePoint: "Needle", threePoint: "Knitting Needle", deck: 'expansion' },
  { onePoint: "Mustang", threePoint: "Wild Mustang", deck: 'expansion' },
  { onePoint: "Mustache", threePoint: "Curly Mustache", deck: 'expansion' },
  { onePoint: "Mud", threePoint: "Mudslide", deck: 'expansion' },
  { onePoint: "Move", threePoint: "Power Moe", deck: 'expansion' },
  { onePoint: "Mouse", threePoint: "Field Mouse", deck: 'expansion' },
  { onePoint: "Moose", threePoint: "Moose Tracks", deck: 'expansion' },
  { onePoint: "Monster", threePoint: "Scary Monster", deck: 'expansion' },
  { onePoint: "Mold", threePoint: "Jell-O Mold", deck: 'expansion' },
  { onePoint: "Mirror", threePoint: "Vanity Mirror", deck: 'expansion' },
  { onePoint: "Mirage", threePoint: "Desert Mirage", deck: 'expansion' },
  { onePoint: "Midnight", threePoint: "Midnight Snack", deck: 'expansion' },
  { onePoint: "Middle", threePoint: "Middle Child", deck: 'expansion' },
  { onePoint: "Melon", threePoint: "Watermelon", deck: 'expansion' },
  { onePoint: "Medium", threePoint: "Medium Rare", deck: 'expansion' },
  { onePoint: "Medal", threePoint: "Gold Medal", deck: 'expansion' },
  { onePoint: "Match", threePoint: "Matchbook", deck: 'expansion' },
  { onePoint: "Marsh", threePoint: "Marshmallow", deck: 'expansion' },
  { onePoint: "Manatee", threePoint: "River Manatee", deck: 'expansion' },
  { onePoint: "Mallet", threePoint: "Rubber Mallet", deck: 'expansion' },
  { onePoint: "Makeup", threePoint: "Makeup Brush", deck: 'expansion' },
  { onePoint: "Mad", threePoint: "Mad Rush", deck: 'expansion' },
  { onePoint: "Lullaby", threePoint: "Gentle Lullaby", deck: 'expansion' },
  { onePoint: "Lost", threePoint: "Lost Keys", deck: 'expansion' },
  { onePoint: "Look", threePoint: "Look Alive", deck: 'expansion' },
  { onePoint: "Log", threePoint: "Log Cabin", deck: 'expansion' },
  { onePoint: "Location", threePoint: "Secret Location", deck: 'expansion' },
  { onePoint: "Lobster", threePoint: "Lobster Claw", deck: 'expansion' },
  { onePoint: "Lobby", threePoint: "Hotel Lobby", deck: 'expansion' },
  { onePoint: "Loan", threePoint: "Bank Loan", deck: 'expansion' },
  { onePoint: "Llama", threePoint: "Spitting Llama", deck: 'expansion' },
  { onePoint: "Harvest", threePoint: "Harvest Season", deck: 'expansion' },
  { onePoint: "Ham", threePoint: "Smoked Ham", deck: 'expansion' },
  { onePoint: "Guest", threePoint: "Guest House", deck: 'expansion' },
  { onePoint: "Guess", threePoint: "Educated Guess", deck: 'expansion' },
  { onePoint: "Grunt", threePoint: "Grunt Work", deck: 'expansion' },
  { onePoint: "Imposter", threePoint: "Imposter Syndrome", deck: 'expansion' },
  { onePoint: "Imaginary", threePoint: "Imaginary Friend", deck: 'expansion' },
  { onePoint: "Hyena", threePoint: "Laughing Hyena", deck: 'expansion' },
  { onePoint: "Hurt", threePoint: "Hurt Feelings", deck: 'expansion' },
  { onePoint: "Humble", threePoint: "Humble Pie", deck: 'expansion' },
  { onePoint: "Neat", threePoint: "Neat Handwriting", deck: 'expansion' },
  { onePoint: "Nanny", threePoint: "Nanny Cam", deck: 'expansion' },
  { onePoint: "List", threePoint: "Guest List", deck: 'expansion' },
  { onePoint: "Line", threePoint: "Power Line", deck: 'expansion' },
  { onePoint: "Lime", threePoint: "Key Lime", deck: 'expansion' },
  { onePoint: "Mill", threePoint: "Windmill", deck: 'expansion' },
  { onePoint: "Migration", threePoint: "Migration Pattern", deck: 'expansion' },
  { onePoint: "Library", threePoint: "Library Card", deck: 'expansion' },
  { onePoint: "Level", threePoint: "Next Level", deck: 'expansion' },
  { onePoint: "Lettuce", threePoint: "Iceberg Lettuce", deck: 'expansion' },
  { onePoint: "Main", threePoint: "Main Street", deck: 'expansion' },
  { onePoint: "Magazine", threePoint: "Magazine Rack", deck: 'expansion' },
  { onePoint: "Lesson", threePoint: "Life Lesson", deck: 'expansion' },
  { onePoint: "Leaf", threePoint: "Four-Leaf Clover", deck: 'expansion' },
  { onePoint: "Layer", threePoint: "Layer Cake", deck: 'expansion' },
  { onePoint: "Lizard", threePoint: "Lizard Lips", deck: 'expansion' },
  { onePoint: "Listen", threePoint: "Listen Up", deck: 'expansion' },
  { onePoint: "Lawn", threePoint: "Lawn Mower", deck: 'expansion' },
  { onePoint: "Lamp", threePoint: "Gas Lamp", deck: 'expansion' },
  { onePoint: "Lamb", threePoint: "Lamb Chop", deck: 'expansion' },
  { onePoint: "Arm", threePoint: "Armadillo", deck: 'expansion' },
  { onePoint: "Asteroid", threePoint: "Asteroid Belt", deck: 'expansion' },
  { onePoint: "Carry", threePoint: "Carry-On", deck: 'expansion' },
  { onePoint: "Casino", threePoint: "Casino Slots", deck: 'expansion' },
  { onePoint: "Elbow", threePoint: "Elbow Grease", deck: 'expansion' },
  { onePoint: "Experiment", threePoint: "Failed Experiment", deck: 'expansion' },
  { onePoint: "Gossip", threePoint: "Juicy Gossip", deck: 'expansion' },
  { onePoint: "Argue", threePoint: "Argue in Circles", deck: 'expansion' },
  { onePoint: "Attempt", threePoint: "Second Attempt", deck: 'expansion' },
  { onePoint: "Canvas", threePoint: "Blank Canvas", deck: 'expansion' },
  { onePoint: "Caterpillar", threePoint: "Hungry Caterpillar", deck: 'expansion' },
  { onePoint: "Eggplant", threePoint: "Eggplant Parmesan", deck: 'expansion' },
  { onePoint: "Fair", threePoint: "Fair Weather", deck: 'expansion' },
  { onePoint: "Gorilla", threePoint: "Silverback Gorilla", deck: 'expansion' },
  { onePoint: "Archery", threePoint: "Archery Range", deck: 'expansion' },
  { onePoint: "Audience", threePoint: "Captive Audience", deck: 'expansion' },
  { onePoint: "Cane", threePoint: "Candy Cane", deck: 'expansion' },
  { onePoint: "Ceremony", threePoint: "Graduation Ceremony", deck: 'expansion' },
  { onePoint: "Eel", threePoint: "Electric Eel", deck: 'expansion' },
  { onePoint: "Falcon", threePoint: "Falcon Wings", deck: 'expansion' },
  { onePoint: "Glue", threePoint: "Glue Stick", deck: 'expansion' },
  { onePoint: "Arch", threePoint: "Balloon Arch", deck: 'expansion' },
  { onePoint: "Avocado", threePoint: "Avocado Toast", deck: 'expansion' },
  { onePoint: "Camel", threePoint: "Camelback", deck: 'expansion' },
  { onePoint: "Chisel", threePoint: "Chiseled Jaw", deck: 'expansion' },
  { onePoint: "Eat", threePoint: "Eating Contest", deck: 'expansion' },
  { onePoint: "Farmer", threePoint: "Farmers' Market", deck: 'expansion' },
  { onePoint: "Giraffe", threePoint: "Giraffe Tongue", deck: 'expansion' },
  { onePoint: "Anvil", threePoint: "Iron Anvil", deck: 'expansion' },
  { onePoint: "Background", threePoint: "Background Image", deck: 'expansion' },
  { onePoint: "Cactus", threePoint: "Cactus Fruit", deck: 'expansion' },
  { onePoint: "Circus", threePoint: "Circus Acrobat", deck: 'expansion' },
  { onePoint: "Eagle", threePoint: "Bald Eagle", deck: 'expansion' },
  { onePoint: "Fart", threePoint: "Silent Fart", deck: 'expansion' },
  { onePoint: "Garlic", threePoint: "Garlic Knot", deck: 'expansion' },
  { onePoint: "Ankle", threePoint: "Sprained Ankle", deck: 'expansion' },
  { onePoint: "Bail", threePoint: "Bailout", deck: 'expansion' },
  { onePoint: "Cab", threePoint: "Yellow Cab", deck: 'expansion' },
  { onePoint: "Clean", threePoint: "Clean Laundry", deck: 'expansion' },
  { onePoint: "Dribble", threePoint: "Double Dribble", deck: 'expansion' },
  { onePoint: "Feast", threePoint: "Holiday Feast", deck: 'expansion' },
  { onePoint: "Gap", threePoint: "Gap-Toothed", deck: 'expansion' },
  { onePoint: "Allowance", threePoint: "Weekly Allowance", deck: 'expansion' },
  { onePoint: "Bait", threePoint: "Fish Bait", deck: 'expansion' },
  { onePoint: "Bamboo", threePoint: "Bamboo Shoot", deck: 'expansion' },
  { onePoint: "Burp", threePoint: "Burpees", deck: 'expansion' },
  { onePoint: "Compare", threePoint: "Nothing Compares", deck: 'expansion' },
  { onePoint: "Dress", threePoint: "Pencil Dress", deck: 'expansion' },
  { onePoint: "Feet", threePoint: "Feet First", deck: 'expansion' },
  { onePoint: "Fuse", threePoint: "Short Fuse", deck: 'expansion' },
  { onePoint: "Allergy", threePoint: "Pollen Allergy", deck: 'expansion' },
  { onePoint: "Beard", threePoint: "Beard Wax", deck: 'expansion' },
  { onePoint: "Bulk", threePoint: "Bulk Order", deck: 'expansion' },
  { onePoint: "Connection", threePoint: "Missed Connection", deck: 'expansion' },
  { onePoint: "Dove", threePoint: "Dovetail", deck: 'expansion' },
  { onePoint: "Figure", threePoint: "Action Figure", deck: 'expansion' },
  { onePoint: "Furniture", threePoint: "Furniture Movers", deck: 'expansion' },
  { onePoint: "Aisle", threePoint: "Frozen Aisle", deck: 'expansion' },
  { onePoint: "Beat", threePoint: "Heartbeat", deck: 'expansion' },
  { onePoint: "Buckle", threePoint: "Belt Buckle", deck: 'expansion' },
  { onePoint: "Cost", threePoint: "Sunk Cost", deck: 'expansion' },
  { onePoint: "Dolphin", threePoint: "Bottlenose Dolphin", deck: 'expansion' },
  { onePoint: "Flamingo", threePoint: "Plastic Flamingo", deck: 'expansion' },
  { onePoint: "Fun", threePoint: "Fun Fact", deck: 'expansion' },
  { onePoint: "Beep", threePoint: "Beep, Beep!", deck: 'expansion' },
  { onePoint: "Brook", threePoint: "Babbling Brook", deck: 'expansion' },
  { onePoint: "Cream", threePoint: "Sour Cream", deck: 'expansion' },
  { onePoint: "Dodge", threePoint: "Dodgeball", deck: 'expansion' },
  { onePoint: "Flat", threePoint: "Flat Screen", deck: 'expansion' },
  { onePoint: "Full", threePoint: "Full Moon", deck: 'expansion' },
  { onePoint: "Bet", threePoint: "Safe Bet", deck: 'expansion' },
  { onePoint: "Broke", threePoint: "Flat Broke", deck: 'expansion' },
  { onePoint: "Crunch", threePoint: "Crunch Time", deck: 'expansion' },
  { onePoint: "Disturb", threePoint: "Do Not Disturb", deck: 'expansion' },
  { onePoint: "Flea", threePoint: "Flea Market", deck: 'expansion' },
  { onePoint: "Frown", threePoint: "Frown Lines", deck: 'expansion' },
  { onePoint: "Blink", threePoint: "Don't Blink", deck: 'expansion' },
  { onePoint: "Broccoli", threePoint: "Steamed Broccoli", deck: 'expansion' },
  { onePoint: "Dare", threePoint: "Daredevil", deck: 'expansion' },
  { onePoint: "Dimples", threePoint: "Cheek Dimples", deck: 'expansion' },
  { onePoint: "Flip", threePoint: "Flip-Flop", deck: 'expansion' },
  { onePoint: "Friday", threePoint: "Friday Night", deck: 'expansion' },
  { onePoint: "Blister", threePoint: "Blister Pack", deck: 'expansion' },
  { onePoint: "Braid", threePoint: "Long Braids", deck: 'expansion' },
  { onePoint: "Deed", threePoint: "Good Deed", deck: 'expansion' },
  { onePoint: "Desserts", threePoint: "Just Desserts", deck: 'expansion' },
  { onePoint: "Follow", threePoint: "Follow Suit", deck: 'expansion' },
  { onePoint: "Fresh", threePoint: "Freshwater", deck: 'expansion' },
  { onePoint: "Board", threePoint: "Boardwalk", deck: 'expansion' },
  { onePoint: "Bolt", threePoint: "Bolt Cutter", deck: 'expansion' },
  { onePoint: "Delivery", threePoint: "Delivery Route", deck: 'expansion' },
  { onePoint: "Department", threePoint: "Clothing Department", deck: 'expansion' },
  { onePoint: "Fox", threePoint: "Sly Fox", deck: 'expansion' },
  { onePoint: "Frame", threePoint: "Window Frame", deck: 'expansion' },
  { onePoint: "Admit", threePoint: "Admit One", deck: 'expansion' },
  { onePoint: "Adventure", threePoint: "Adventure Gear", deck: 'expansion' },
  { onePoint: "Acting", threePoint: "Method Acting", deck: 'expansion' },
  { onePoint: "Cork", threePoint: "Corkboard", deck: 'expansion' },
  { onePoint: "Donkey", threePoint: "Donkey Kick", deck: 'expansion' },
  { onePoint: "Find", threePoint: "Find Out", deck: 'expansion' },
  { onePoint: "Doodle", threePoint: "Notebook Doodle", deck: 'expansion' },
  { onePoint: "Shovel", threePoint: "Snow Shovel", deck: 'expansion' },
  { onePoint: "Honey", threePoint: "Honey Badger", deck: 'expansion' },
  { onePoint: "Hail", threePoint: "Hail Mary", deck: 'expansion' },
  { onePoint: "Dunk", threePoint: "Slam Dunk", deck: 'expansion' },
  { onePoint: "Beet", threePoint: "Beet Juice", deck: 'expansion' },
  { onePoint: "Chili", threePoint: "Chili Powder", deck: 'expansion' },
  { onePoint: "Lance", threePoint: "Freelancer", deck: 'expansion' },
  { onePoint: "Cologne", threePoint: "Musky Cologne", deck: 'expansion' },
  { onePoint: "Shave", threePoint: "Shaving Cream", deck: 'expansion' },
  { onePoint: "Dump", threePoint: "Dump Truck", deck: 'expansion' },
  { onePoint: "Foundation", threePoint: "Solid Foundation", deck: 'expansion' },
  { onePoint: "Chart", threePoint: "Pie Chart", deck: 'expansion' },
  { onePoint: "Hammer", threePoint: "Sledge Hammer", deck: 'expansion' },
  { onePoint: "Saw", threePoint: "Seesaw", deck: 'expansion' },
  { onePoint: "Ruler", threePoint: "Metric Ruler", deck: 'expansion' },
  { onePoint: "Flash", threePoint: "Flashlight", deck: 'expansion' },
  { onePoint: "Tool", threePoint: "Power Tool", deck: 'expansion' },
  { onePoint: "Axe", threePoint: "Axe Throwing", deck: 'expansion' },
  { onePoint: "Pin", threePoint: "Pinball Machine", deck: 'expansion' },
  { onePoint: "Trust", threePoint: "Brain Trust", deck: 'expansion' },
  { onePoint: "Peak", threePoint: "Mountain Peak", deck: 'expansion' },
  { onePoint: "Hill", threePoint: "Steep Hill", deck: 'expansion' },
  { onePoint: "Guide", threePoint: "Trail Guide", deck: 'expansion' },
  { onePoint: "Rush", threePoint: "Rush Hour", deck: 'expansion' },
  { onePoint: "Victory", threePoint: "Victory Lap", deck: 'expansion' },
  { onePoint: "Equal", threePoint: "Equal Pay", deck: 'expansion' },
  { onePoint: "Wonder", threePoint: "Wold WOnder", deck: 'expansion' },
  { onePoint: "Stage", threePoint: "Stage Fright", deck: 'expansion' },
  { onePoint: "Craft", threePoint: "Craft Beer", deck: 'expansion' },
  { onePoint: "Meet", threePoint: "Swim Meet", deck: 'expansion' },
  { onePoint: "Bunch", threePoint: "Honeybunch", deck: 'expansion' },
  { onePoint: "Motor", threePoint: "Motor Oil", deck: 'expansion' },
  { onePoint: "Order", threePoint: "Marching Order", deck: 'expansion' },
  { onePoint: "Recess", threePoint: "Recess Bell", deck: 'expansion' },
  { onePoint: "Mall", threePoint: "Mall Escalator", deck: 'expansion' },
  { onePoint: "Rainbow", threePoint: "Pride Rainbow", deck: 'expansion' },
  { onePoint: "Natural", threePoint: "Natural Curls", deck: 'expansion' },
  { onePoint: "Collection", threePoint: "Coin Collection", deck: 'expansion' },
  { onePoint: "Event", threePoint: "Main Event", deck: 'expansion' },
  { onePoint: "Sore", threePoint: "Sore Loser", deck: 'expansion' },
  { onePoint: "Sports", threePoint: "Sports Announcer", deck: 'expansion' },
  { onePoint: "Screen", threePoint: "Screen Protector", deck: 'expansion' },
  { onePoint: "Cupcake", threePoint: "Cupcake Tower", deck: 'expansion' },
  { onePoint: "Heal", threePoint: "Healing Words", deck: 'expansion' },
  { onePoint: "Lecture", threePoint: "Lecture Hall", deck: 'expansion' },
  { onePoint: "Risk", threePoint: "Calculated Risk", deck: 'expansion' },
  { onePoint: "Sail", threePoint: "Set Sail", deck: 'expansion' },
  { onePoint: "Grade", threePoint: "Test Grade", deck: 'expansion' },
  { onePoint: "Rest", threePoint: "Rest Stop", deck: 'expansion' },
  { onePoint: "Hoop", threePoint: "Hoop Earrings", deck: 'expansion' },
  { onePoint: "Spy", threePoint: "Spyglass", deck: 'expansion' },
  { onePoint: "Total", threePoint: "Grand Total", deck: 'expansion' },
  { onePoint: "Tank", threePoint: "Think Tank", deck: 'expansion' },
  { onePoint: "Studio", threePoint: "Studio Apartment", deck: 'expansion' },
  { onePoint: "Range", threePoint: "Close Range", deck: 'expansion' },
  { onePoint: "Carousel", threePoint: "Carousel Horse", deck: 'expansion' },
  { onePoint: "Slide", threePoint: "Playground Slide", deck: 'expansion' },
  { onePoint: "Pay", threePoint: "Pay Attention", deck: 'expansion' },
  { onePoint: "Habit", threePoint: "Bad Habit", deck: 'expansion' },
  { onePoint: "Patience", threePoint: "Infinite Patience", deck: 'expansion' },
  { onePoint: "Theater", threePoint: "Movie Theater", deck: 'expansion' },
  { onePoint: "Pocket", threePoint: "Pickpocket", deck: 'expansion' },
  { onePoint: "Point", threePoint: "Viewpoint", deck: 'expansion' },
  { onePoint: "Powder", threePoint: "Powder Keg", deck: 'expansion' },
  { onePoint: "Railroad", threePoint: "Railroad Track", deck: 'expansion' },
  { onePoint: "Hide", threePoint: "Rawhide", deck: 'expansion' },
  { onePoint: "Red", threePoint: "Red Velvet", deck: 'expansion' },
  { onePoint: "Sample", threePoint: "Free Sample", deck: 'expansion' },
  { onePoint: "Worm", threePoint: "Gummy Worm", deck: 'expansion' },
  { onePoint: "Flood", threePoint: "Floodgate", deck: 'expansion' },
  { onePoint: "Floor", threePoint: "Floor Plan", deck: 'expansion' },
  { onePoint: "Folder", threePoint: "File Folder", deck: 'expansion' },
  { onePoint: "Folk", threePoint: "Folk Story", deck: 'expansion' },
  { onePoint: "Fortune", threePoint: "Fortune Teller", deck: 'expansion' },
  { onePoint: "Gate", threePoint: "Tailgate", deck: 'expansion' },
  { onePoint: "Gem", threePoint: "Hidden Gem", deck: 'expansion' },
  { onePoint: "Good", threePoint: "Goodbye", deck: 'expansion' },
  { onePoint: "Quilt", threePoint: "Patchwork Quilt", deck: 'expansion' },
  { onePoint: "Path", threePoint: "Path Less Traveled", deck: 'expansion' },
  { onePoint: "Spine", threePoint: "Book Spine", deck: 'expansion' },
  { onePoint: "Couch", threePoint: "Couch Potato", deck: 'expansion' },
  { onePoint: "Den", threePoint: "Thieves Den", deck: 'expansion' },
  { onePoint: "Dock", threePoint: "Dockyard", deck: 'expansion' },
  { onePoint: "Van", threePoint: "Minivan", deck: 'expansion' },
  { onePoint: "Rat", threePoint: "Packrat", deck: 'expansion' },
  { onePoint: "Drift", threePoint: "Driftwood", deck: 'expansion' },
  { onePoint: "Expert", threePoint: "Expert Opinion", deck: 'expansion' },
  { onePoint: "Check", threePoint: "Fact Check", deck: 'expansion' },
  { onePoint: "Fan", threePoint: "Fanfare", deck: 'expansion' },
  { onePoint: "Balance", threePoint: "Zero Balance", deck: 'expansion' },
  { onePoint: "Belief", threePoint: "Beyond Belief", deck: 'expansion' },
  { onePoint: "Berry", threePoint: "Elderberry", deck: 'expansion' },
  { onePoint: "Iron", threePoint: "Cast Iron", deck: 'expansion' },
  { onePoint: "Blank", threePoint: "Blank Slate", deck: 'expansion' },
  { onePoint: "Pit", threePoint: "Bonfire Pit", deck: 'expansion' },
  { onePoint: "Tulip", threePoint: "Tulip Bulb", deck: 'expansion' },
  { onePoint: "Catch", threePoint: "Catch Up", deck: 'expansion' },
  { onePoint: "Center", threePoint: "City Center", deck: 'expansion' },
  { onePoint: "Tug", threePoint: "Tug Boat", deck: 'expansion' },
  { onePoint: "Crow", threePoint: "Scarecrow", deck: 'expansion' },
  { onePoint: "Exit", threePoint: "Exit Sign", deck: 'expansion' },
  { onePoint: "Reset", threePoint: "Reset Button", deck: 'expansion' },
  { onePoint: "Tissue", threePoint: "Tissue Paper", deck: 'expansion' },
  { onePoint: "Weather", threePoint: "Weather Report", deck: 'expansion' },
  { onePoint: "Steak", threePoint: "Rib Eye Steak", deck: 'expansion' },
  { onePoint: "Shelter", threePoint: "Animal Shelter", deck: 'expansion' },
  { onePoint: "Wax", threePoint: "Earwax", deck: 'expansion' },
  { onePoint: "Tire", threePoint: "Spare Tire", deck: 'expansion' },
  { onePoint: "Cabbage", threePoint: "Cabbage Patch", deck: 'expansion' },
  { onePoint: "Bronze", threePoint: "Bronze Statue", deck: 'expansion' },
  { onePoint: "Internet", threePoint: "Internet Speed", deck: 'expansion' },
  { onePoint: "Fridge", threePoint: "Fridge Magnet", deck: 'expansion' },
  { onePoint: "Goal", threePoint: "Squad Goals", deck: 'expansion' },
  { onePoint: "Study", threePoint: "Quick Study", deck: 'expansion' },
  { onePoint: "Television", threePoint: "National Television", deck: 'expansion' },
  { onePoint: "Ability", threePoint: "Psychic Ability", deck: 'expansion' },
  { onePoint: "History", threePoint: "Natural History", deck: 'expansion' },
  { onePoint: "Sting", threePoint: "Stingray", deck: 'expansion' },
  { onePoint: "Estate", threePoint: "Real Estate", deck: 'expansion' },
  { onePoint: "Circuit", threePoint: "Circuit Board", deck: 'expansion' },
  { onePoint: "Pear", threePoint: "Pear Tree", deck: 'expansion' },
  { onePoint: "Soul", threePoint: "Soul Mate", deck: 'expansion' },
  { onePoint: "Fiction", threePoint: "Fan Fiction", deck: 'expansion' },
  { onePoint: "Dune", threePoint: "Dune Buggy", deck: 'expansion' },
  { onePoint: "Sliver", threePoint: "Sliver of Hope", deck: 'expansion' },
  { onePoint: "Skeleton", threePoint: "Skeleton Crew", deck: 'expansion' },
  { onePoint: "Bush", threePoint: "Thornbush", deck: 'expansion' },
  { onePoint: "Fantasy", threePoint: "Fantasy Football", deck: 'expansion' },
  { onePoint: "Hug", threePoint: "Bear Hug", deck: 'expansion' },
  { onePoint: "Purse", threePoint: "Purse Organizer", deck: 'expansion' },
  { onePoint: "Fate", threePoint: "Twist of Fate", deck: 'expansion' },
  { onePoint: "Mushroom", threePoint: "Oyster Mushroom", deck: 'expansion' },
  { onePoint: "Whistle", threePoint: "Whistleblower", deck: 'expansion' },
  { onePoint: "Evening", threePoint: "Evening Wear", deck: 'expansion' },
  { onePoint: "Bean", threePoint: "Jelly Bean", deck: 'expansion' },
  { onePoint: "Tarot", threePoint: "Tarot Card", deck: 'expansion' },
  { onePoint: "Blast", threePoint: "Blast Off", deck: 'expansion' },
  { onePoint: "Dish", threePoint: "Deep-Dish", deck: 'expansion' },
  { onePoint: "Spice", threePoint: "Spiced Wine", deck: 'expansion' },
  { onePoint: "Story", threePoint: "Storyteller", deck: 'expansion' },
  { onePoint: "Father", threePoint: "Founding Father", deck: 'expansion' },
  { onePoint: "Coat", threePoint: "Trench Coat", deck: 'expansion' },
  { onePoint: "Common", threePoint: "Common sense", deck: 'expansion' },
  { onePoint: "Passage", threePoint: "Underground Passage", deck: 'expansion' },
  { onePoint: "Theory", threePoint: "String Theory", deck: 'expansion' },
  { onePoint: "Pencil", threePoint: "Pencil Lead", deck: 'expansion' },
  { onePoint: "Donut", threePoint: "Donut Break", deck: 'expansion' },
  { onePoint: "Heaven", threePoint: "Seventh Heaven", deck: 'expansion' },
  { onePoint: "Village", threePoint: "Santa's Village", deck: 'expansion' },
  { onePoint: "News", threePoint: "News Anchor", deck: 'expansion' },
  { onePoint: "Complaint", threePoint: "Noise Complaint", deck: 'expansion' },
  { onePoint: "Fabric", threePoint: "Fabric Softener", deck: 'expansion' },
  { onePoint: "Rug", threePoint: "Rug Burn", deck: 'expansion' },
  { onePoint: "Clue", threePoint: "Clueless", deck: 'expansion' },
  { onePoint: "Roof", threePoint: "Under One Roof", deck: 'expansion' },
  { onePoint: "Number", threePoint: "Apartment Number", deck: 'expansion' },
  { onePoint: "Measure", threePoint: "Tape Measure", deck: 'expansion' },
  { onePoint: "Robe", threePoint: "Bathrobe", deck: 'expansion' },
  { onePoint: "Brunch", threePoint: "Sunday Brunch", deck: 'expansion' },
  { onePoint: "Policy", threePoint: "Open Door Policy", deck: 'expansion' },
  { onePoint: "Frenzy", threePoint: "Feeding Frenzy", deck: 'expansion' },
  { onePoint: "Carnival", threePoint: "Carnival Prize", deck: 'expansion' },
  { onePoint: "Boost", threePoint: "Booster Seat", deck: 'expansion' },
  { onePoint: "Can", threePoint: "Soda Can", deck: 'expansion' },
  { onePoint: "Wallet", threePoint: "Wallet Chain", deck: 'expansion' },
  { onePoint: "Seal", threePoint: "Wax Seal", deck: 'expansion' },
  { onePoint: "Goose", threePoint: "Goose Bumps", deck: 'expansion' },
  { onePoint: "Submarine", threePoint: "Nuclear Submarine", deck: 'expansion' },
  { onePoint: "Language", threePoint: "Sign Language", deck: 'expansion' },
  { onePoint: "Rattle", threePoint: "Baby Rattle", deck: 'expansion' },
  { onePoint: "Battery", threePoint: "Battery Charger", deck: 'expansion' },
  { onePoint: "Brass", threePoint: "Brass Knuckles", deck: 'expansion' },
  { onePoint: "Cartoon", threePoint: "Cartoon Strip", deck: 'expansion' },
  { onePoint: "Carbon", threePoint: "Carbon Filter", deck: 'expansion' },
  { onePoint: "Quality", threePoint: "Quality Assurance", deck: 'expansion' },
  { onePoint: "Initiative", threePoint: "Take Initiative", deck: 'expansion' },
  { onePoint: "Leopard", threePoint: "Leopard Print", deck: 'expansion' },
  { onePoint: "Flow", threePoint: "Lava Flow", deck: 'expansion' },
  { onePoint: "Waste", threePoint: "Waste Treatment", deck: 'expansion' },
  { onePoint: "Sea", threePoint: "Sea Breeze", deck: 'expansion' },
  { onePoint: "Knife", threePoint: "Butter Knife", deck: 'expansion' },
  { onePoint: "Parent", threePoint: "Grandparent", deck: 'expansion' },
  { onePoint: "Mistake", threePoint: "Honest Mistake", deck: 'expansion' },
  { onePoint: "Tie", threePoint: "Tie-Dye", deck: 'expansion' },
  { onePoint: "Change", threePoint: "Loose Change", deck: 'expansion' },
  { onePoint: "Product", threePoint: "Product Design", deck: 'expansion' },
  { onePoint: "Printer", threePoint: "Laser Printer", deck: 'expansion' },
  { onePoint: "Marble", threePoint: "Marble Bust", deck: 'expansion' },
  { onePoint: "Zone", threePoint: "Time Zone", deck: 'expansion' },
  { onePoint: "Attack", threePoint: "Sneak Attack", deck: 'expansion' },
  { onePoint: "Cheer", threePoint: "Cheerleader", deck: 'expansion' },
  { onePoint: "Grave", threePoint: "Gravedigger", deck: 'expansion' },
  { onePoint: "Spell", threePoint: "Dizzy Spell", deck: 'expansion' },
  { onePoint: "Reunion", threePoint: "High School Reunion", deck: 'expansion' },
  { onePoint: "Puzzle", threePoint: "Jigsaw Puzzle", deck: 'expansion' },
  { onePoint: "Rig", threePoint: "Gaming Rig", deck: 'expansion' },
  { onePoint: "Science", threePoint: "Science Fiction", deck: 'expansion' },
  { onePoint: "Coconut", threePoint: "Shredded Coconut", deck: 'expansion' },
  { onePoint: "Duet", threePoint: "Violin Duet", deck: 'expansion' },
  { onePoint: "Gut", threePoint: "Gut Check", deck: 'expansion' },
  { onePoint: "Chip", threePoint: "Chipmunk", deck: 'expansion' },
  { onePoint: "Ear", threePoint: "Earmuffs", deck: 'expansion' },
  { onePoint: "Engineer", threePoint: "Civil Engineer", deck: 'expansion' },
  { onePoint: "Error", threePoint: "Fatal Error", deck: 'expansion' },
  { onePoint: "Energy", threePoint: "Clean Energy", deck: 'expansion' },
  { onePoint: "Education", threePoint: "Higher Education", deck: 'expansion' },
  { onePoint: "Duel", threePoint: "Pistol Duel", deck: 'expansion' },
  { onePoint: "Anchor", threePoint: "Raise Anchor", deck: 'expansion' },
  { onePoint: "Editor", threePoint: "Copy Editor", deck: 'expansion' },
  { onePoint: "Deodorant", threePoint: "Spray Deodorant", deck: 'expansion' },
  { onePoint: "Crust", threePoint: "Upper Crust", deck: 'expansion' },
  { onePoint: "Smile", threePoint: "Warm Smile", deck: 'expansion' },
  { onePoint: "Arrow", threePoint: "Straight Arrow", deck: 'expansion' },
  { onePoint: "Porcupine", threePoint: "Porcupine Quill", deck: 'expansion' },
  { onePoint: "Exam", threePoint: "Physical Exam", deck: 'expansion' },
  { onePoint: "Quick", threePoint: "Quicksand", deck: 'expansion' },
  { onePoint: "Response", threePoint: "First Response Team", deck: 'expansion' },
  { onePoint: "Grand", threePoint: "Grand Entrance", deck: 'expansion' },
  { onePoint: "Bronco", threePoint: "Bucking Bronco", deck: 'expansion' },
  { onePoint: "Well", threePoint: "Wishing Well", deck: 'expansion' },
  { onePoint: "Inflation", threePoint: "Inflation Rate", deck: 'expansion' },
  { onePoint: "Rescue", threePoint: "Rescue Mission", deck: 'expansion' },
  { onePoint: "Chase", threePoint: "High-Speed Chase", deck: 'expansion' },
  { onePoint: "Mark", threePoint: "Landmark", deck: 'expansion' },
  { onePoint: "Sister", threePoint: "Little Sister", deck: 'expansion' },
  { onePoint: "Streak", threePoint: "Winning Streak", deck: 'expansion' },
  { onePoint: "Release", threePoint: "Release Valve", deck: 'expansion' },
  { onePoint: "Microscope", threePoint: "Microscope Slide", deck: 'expansion' },
  { onePoint: "Half", threePoint: "Better Half", deck: 'expansion' },
  { onePoint: "Pour", threePoint: "Heavy Pour", deck: 'expansion' },
  { onePoint: "Tea", threePoint: "Bubble Tea", deck: 'expansion' },
  { onePoint: "Hockey", threePoint: "Field Hockey", deck: 'expansion' },
  { onePoint: "Care", threePoint: "Caregiver", deck: 'expansion' },
  { onePoint: "Bonus", threePoint: "Bonus Round", deck: 'expansion' },
  { onePoint: "Step", threePoint: "Stepladder", deck: 'expansion' },
  { onePoint: "Nature", threePoint: "Force of Nature", deck: 'expansion' },
  { onePoint: "Witch", threePoint: "Witches' Coven", deck: 'expansion' },
  { onePoint: "Pen", threePoint: "Gel Pen", deck: 'expansion' },
  { onePoint: "Jump", threePoint: "Jump Scare", deck: 'expansion' },
  { onePoint: "Picture", threePoint: "Picture Perfect", deck: 'expansion' },
  { onePoint: "Shield", threePoint: "Shield Bearer", deck: 'expansion' },
  { onePoint: "Sled", threePoint: "Dogsled", deck: 'expansion' },
  { onePoint: "Spaghetti", threePoint: "Spaghetti Western", deck: 'expansion' },
  { onePoint: "Labor", threePoint: "Labor Union", deck: 'expansion' },
  { onePoint: "Snap", threePoint: "Snapshot", deck: 'expansion' },
  { onePoint: "Moth", threePoint: "Mothball", deck: 'expansion' },
  { onePoint: "Campus", threePoint: "College Campus", deck: 'expansion' },
  { onePoint: "Tide", threePoint: "Riptide", deck: 'expansion' },
  { onePoint: "Sneeze", threePoint: "Sneeze Guard", deck: 'expansion' },
  { onePoint: "Soap", threePoint: "Soap Opera", deck: 'expansion' },
  { onePoint: "Staircase", threePoint: "Spiral Staircase", deck: 'expansion' },
  { onePoint: "Coin", threePoint: "Coin Toss", deck: 'expansion' },
  { onePoint: "Robin", threePoint: "Round Robin", deck: 'expansion' },
  { onePoint: "Child", threePoint: "Child Actor", deck: 'expansion' },
  { onePoint: "Puff", threePoint: "Puffin", deck: 'expansion' },
  { onePoint: "Organ", threePoint: "Organ Donor", deck: 'expansion' },
  { onePoint: "Laugh", threePoint: "Laugh Out Loud", deck: 'expansion' },
  { onePoint: "Pine", threePoint: "Pine Cone", deck: 'expansion' },
  { onePoint: "Mop", threePoint: "Mop Bucket", deck: 'expansion' },
  { onePoint: "Lavender", threePoint: "Lavender Incense", deck: 'expansion' },
  { onePoint: "Auction", threePoint: "Auction House", deck: 'expansion' },
  { onePoint: "Insurance", threePoint: "Home Insurance", deck: 'expansion' },
  { onePoint: "Company", threePoint: "Good Company", deck: 'expansion' },
  { onePoint: "Woman", threePoint: "Confident Woman", deck: 'expansion' },
  { onePoint: "Cushion", threePoint: "Couch Cushion", deck: 'expansion' },
  { onePoint: "Bow Tie", threePoint: "Bow Tie Pasta", deck: 'expansion' },
  { onePoint: "Corn", threePoint: "Corncob", deck: 'expansion' },
  { onePoint: "Feather", threePoint: "Feather Duster", deck: 'expansion' },
  { onePoint: "Year", threePoint: "Leap Year", deck: 'expansion' },
  { onePoint: "Sigh", threePoint: "Deep Sigh", deck: 'expansion' },
  { onePoint: "Necklace", threePoint: "Diamond Necklace", deck: 'expansion' },
  { onePoint: "Tomato", threePoint: "Tomato Soup", deck: 'expansion' },
  { onePoint: "Trail", threePoint: "Trail Marker", deck: 'expansion' },
  { onePoint: "Knock", threePoint: "Knockout", deck: 'expansion' },
  { onePoint: "Night", threePoint: "Nightmare", deck: 'expansion' },
  { onePoint: "Memory", threePoint: "Memory Lane", deck: 'expansion' },
  { onePoint: "Surprise", threePoint: "Surprise Party", deck: 'expansion' },
  { onePoint: "Cartridge", threePoint: "Game Cartridge", deck: 'expansion' },
  { onePoint: "Buzz", threePoint: "Buzz Word", deck: 'expansion' },
  { onePoint: "Clap", threePoint: "Clap Back", deck: 'expansion' },
  { onePoint: "Delay", threePoint: "Signal Delay", deck: 'expansion' },
  { onePoint: "Camp", threePoint: "Campgrounds", deck: 'expansion' },
  { onePoint: "Olive", threePoint: "Olive Oil", deck: 'expansion' },
  { onePoint: "Sky", threePoint: "Skydiving", deck: 'expansion' },
  { onePoint: "Fee", threePoint: "Late Fee", deck: 'expansion' },
  { onePoint: "Offer", threePoint: "Counteroffer", deck: 'expansion' },
  { onePoint: "Kid", threePoint: "Cool Kid", deck: 'expansion' },
  { onePoint: "Tail", threePoint: "Ponytail", deck: 'expansion' },
  { onePoint: "Week", threePoint: "Welcome Week", deck: 'expansion' },
  { onePoint: "Catapult", threePoint: "Wooden Catapult", deck: 'expansion' },
  { onePoint: "Ad", threePoint: "Ad Agency", deck: 'expansion' },
  { onePoint: "Goat", threePoint: "Scapegoat", deck: 'expansion' },
  { onePoint: "Record", threePoint: "Broken Record", deck: 'expansion' },
  { onePoint: "Moment", threePoint: "Eureka Moment", deck: 'expansion' },
  { onePoint: "Stream", threePoint: "Steady Stream", deck: 'expansion' },
  { onePoint: "Weed", threePoint: "Tumbleweed", deck: 'expansion' },
  { onePoint: "Class", threePoint: "Classmate", deck: 'expansion' },
  { onePoint: "Store", threePoint: "Dollar Store", deck: 'expansion' },
  { onePoint: "Entry", threePoint: "Entry Point", deck: 'expansion' },
  { onePoint: "Cast", threePoint: "Castaway", deck: 'expansion' },
  { onePoint: "Code", threePoint: "Code Red", deck: 'expansion' },
  { onePoint: "Comfort", threePoint: "Comfort Food", deck: 'expansion' },
  { onePoint: "Joke", threePoint: "Inside Joke", deck: 'expansion' },
  { onePoint: "Game", threePoint: "Game Night", deck: 'expansion' },
  { onePoint: "Forest", threePoint: "Forest Clearing", deck: 'expansion' },
  { onePoint: "Fountain", threePoint: "Water Fountain", deck: 'expansion' },
  { onePoint: "Grace", threePoint: "Amazing Grace", deck: 'expansion' },
  { onePoint: "Exhibit", threePoint: "Art Exhibit", deck: 'expansion' },
  { onePoint: "Microwave", threePoint: "Microwave Oven", deck: 'expansion' },
  { onePoint: "Border", threePoint: "Border Collie", deck: 'expansion' },
  { onePoint: "Charity", threePoint: "Charity Drive", deck: 'expansion' },
  { onePoint: "Broom", threePoint: "Broomstick", deck: 'expansion' },
  { onePoint: "Acid", threePoint: "Battery Acid", deck: 'expansion' },
  { onePoint: "Cold", threePoint: "Cold Brew", deck: 'expansion' },
  { onePoint: "Play", threePoint: "Playback", deck: 'expansion' },
  { onePoint: "Hook", threePoint: "Grappling Hook", deck: 'expansion' },
  { onePoint: "Community", threePoint: "Community Leader", deck: 'expansion' },
  { onePoint: "Book", threePoint: "Bookcase", deck: 'expansion' },
  { onePoint: "Pig", threePoint: "Guinea Pig", deck: 'expansion' },
  { onePoint: "Ram", threePoint: "Battering Ram", deck: 'expansion' },
  { onePoint: "Clock", threePoint: "Grandfather Clock", deck: 'expansion' },
  { onePoint: "Razor", threePoint: "Razor Blade", deck: 'expansion' },
  { onePoint: "Fruit", threePoint: "Fruit Smoothie", deck: 'expansion' },
  { onePoint: "Bat", threePoint: "Vampire Bat", deck: 'expansion' },
  { onePoint: "Role", threePoint: "Role-play", deck: 'expansion' },
  { onePoint: "Reading", threePoint: "Palm Reading", deck: 'expansion' },
  { onePoint: "Brace", threePoint: "Arm Brace", deck: 'expansion' },
  { onePoint: "Fix", threePoint: "Easy Fix", deck: 'expansion' },
  { onePoint: "Boss", threePoint: "Boss Battle", deck: 'expansion' },
  { onePoint: "Spark", threePoint: "Spark Plug", deck: 'expansion' },
  { onePoint: "Beam", threePoint: "Balance Beam", deck: 'expansion' },
  { onePoint: "Reef", threePoint: "Coral Reef", deck: 'expansion' },
  { onePoint: "Silver", threePoint: "Quicksilver", deck: 'expansion' },
  { onePoint: "Cooking", threePoint: "Cooking Class", deck: 'expansion' },
  { onePoint: "Chop", threePoint: "Chopsticks", deck: 'expansion' },
  { onePoint: "Model", threePoint: "Role Model", deck: 'expansion' },
  { onePoint: "Fog", threePoint: "Foghorn", deck: 'expansion' },
  { onePoint: "Hog", threePoint: "Hedgehog", deck: 'expansion' },
  { onePoint: "Foam", threePoint: "Foam Mattress", deck: 'expansion' },
  { onePoint: "Cabin", threePoint: "Cabin Fever", deck: 'expansion' },
  { onePoint: "Stampede", threePoint: "Buffalo Stampede", deck: 'expansion' },
  { onePoint: "Coast", threePoint: "Rollercoaster", deck: 'expansion' },
  { onePoint: "Trailer", threePoint: "Tractor Trailer", deck: 'expansion' },
  { onePoint: "Cheek", threePoint: "Tongue-in-Cheek", deck: 'expansion' },
  { onePoint: "Media", threePoint: "Social Media", deck: 'expansion' },
  { onePoint: "Blaze", threePoint: "Trailblazer", deck: 'expansion' },
  { onePoint: "Canoe", threePoint: "Canoe Paddle", deck: 'expansion' },
  { onePoint: "Formal", threePoint: "Formal Introduction", deck: 'expansion' },
  { onePoint: "Soda", threePoint: "Baking Soda", deck: 'expansion' },
  { onePoint: "Spirit", threePoint: "Kindred Spirit", deck: 'expansion' },
  { onePoint: "Rodeo", threePoint: "Rodeo Clown", deck: 'expansion' },
  { onePoint: "Repair", threePoint: "Repair Kit", deck: 'expansion' },
  { onePoint: "Speech", threePoint: "Free Speech", deck: 'expansion' },
  { onePoint: "Clothing", threePoint: "Clothing Rack", deck: 'expansion' },
  { onePoint: "Burn", threePoint: "Burn Mark", deck: 'expansion' },
  { onePoint: "Girl", threePoint: "Gamer Girl", deck: 'expansion' },
  { onePoint: "Bouquet", threePoint: "Flower Bouquet", deck: 'expansion' },
  { onePoint: "Cannon", threePoint: "Cannonball", deck: 'expansion' },
  { onePoint: "Peanut", threePoint: "Peanut Butter", deck: 'expansion' },
  { onePoint: "Rear", threePoint: "Rear-End", deck: 'expansion' },
  { onePoint: "Slap", threePoint: "Slapdash", deck: 'expansion' },
  { onePoint: "Towel", threePoint: "Slapdash Towel", deck: 'expansion' },
  { onePoint: "Retreat", threePoint: "Annual Retreat", deck: 'expansion' },
  { onePoint: "Car", threePoint: "Trolley Car", deck: 'expansion' },
  { onePoint: "Bull", threePoint: "Bulldozer", deck: 'expansion' },
  { onePoint: "Pod", threePoint: "Podcast", deck: 'expansion' },
  { onePoint: "Buffalo", threePoint: "Buffalo Wings", deck: 'expansion' },
  { onePoint: "Straw", threePoint: "Last Straw", deck: 'expansion' },
  { onePoint: "Disk", threePoint: "Floppy Disk", deck: 'expansion' },
  { onePoint: "Desk", threePoint: "Standing Desk", deck: 'expansion' },
  { onePoint: "Dig", threePoint: "Dig Site", deck: 'expansion' },
  { onePoint: "Deck", threePoint: "Poop Deck", deck: 'expansion' },
  { onePoint: "Deal", threePoint: "Done Deal", deck: 'expansion' },
  { onePoint: "Edge", threePoint: "Cutting Edge", deck: 'expansion' },
  { onePoint: "Diet", threePoint: "Paleo Diet", deck: 'expansion' },
  { onePoint: "Dip", threePoint: "Double Dip", deck: 'expansion' },
  { onePoint: "Deep", threePoint: "Deep Dive", deck: 'expansion' },
  { onePoint: "Danger", threePoint: "Danger Zone", deck: 'expansion' },
  { onePoint: "Donation", threePoint: "Food Donation", deck: 'expansion' },
  { onePoint: "Drawer", threePoint: "False Drawer", deck: 'expansion' },
  { onePoint: "Diver", threePoint: "Scuba Diver", deck: 'expansion' },
  { onePoint: "Drama", threePoint: "Drama Club", deck: 'expansion' },
  { onePoint: "Drop", threePoint: "Dewdrop", deck: 'expansion' },
  { onePoint: "Bridge", threePoint: "Drawbridge", deck: 'expansion' },
  { onePoint: "Drain", threePoint: "Drainpipe", deck: 'expansion' },
  { onePoint: "Doll", threePoint: "Nesting Doll", deck: 'expansion' },
  { onePoint: "Dragon", threePoint: "Bearded Dragon", deck: 'expansion' },
  { onePoint: "Dozen", threePoint: "Baker's Dozen", deck: 'expansion' },
  { onePoint: "Group", threePoint: "Focus Group", deck: 'expansion' },
  { onePoint: "Guard", threePoint: "Crossing Guard", deck: 'expansion' },
  { onePoint: "Glow", threePoint: "Glow Up", deck: 'expansion' },
  { onePoint: "Grind", threePoint: "Daily Grind", deck: 'expansion' },
  { onePoint: "Gift", threePoint: "Anniversary Gift", deck: 'expansion' },
  { onePoint: "Grape", threePoint: "Grapevine", deck: 'expansion' },
  { onePoint: "Giggle", threePoint: "Giggle Fit", deck: 'expansion' },
  { onePoint: "Dust", threePoint: "Dust Storm", deck: 'expansion' },
  { onePoint: "Flour", threePoint: "All-Purpose Flour", deck: 'expansion' },
  { onePoint: "Guilty", threePoint: "Guilty Conscience", deck: 'expansion' },
  { onePoint: "Face", threePoint: "Facelift", deck: 'expansion' },
  { onePoint: "Flag", threePoint: "Pirate Flag", deck: 'expansion' },
  { onePoint: "Film", threePoint: "Film Reel", deck: 'expansion' },
  { onePoint: "Flight", threePoint: "Flight Layover", deck: 'expansion' },
  { onePoint: "Essay", threePoint: "College Essay", deck: 'expansion' },
  { onePoint: "Escape", threePoint: "Escape Hatch", deck: 'expansion' },
  { onePoint: "Branch", threePoint: "Tree Branch", deck: 'expansion' },
  { onePoint: "Jury", threePoint: "Jury Duty", deck: 'expansion' },
  { onePoint: "Elevator", threePoint: "Elevator Music", deck: 'expansion' },
  { onePoint: "Curtain", threePoint: "Curtain Call", deck: 'expansion' },
  { onePoint: "Curve", threePoint: "Grading Curve", deck: 'expansion' },
  { onePoint: "Cruise", threePoint: "Luxury Cruise", deck: 'expansion' },
  { onePoint: "Crime", threePoint: "True Crime", deck: 'expansion' },
  { onePoint: "Crown", threePoint: "Royal Crown", deck: 'expansion' },
  { onePoint: "Cricket", threePoint: "Cricket Bat", deck: 'expansion' },
  { onePoint: "Creature", threePoint: "Creature Comfort", deck: 'expansion' },
  { onePoint: "Howl", threePoint: "Wolf Howl", deck: 'expansion' },
  { onePoint: "Cocktail", threePoint: "Shrimp Cocktail", deck: 'expansion' },
  { onePoint: "Crocodile", threePoint: "Crocodile Tears", deck: 'expansion' },
  { onePoint: "Test", threePoint: "Crash Test Dummy", deck: 'expansion' },
  { onePoint: "Crane", threePoint: "Crane Operator", deck: 'expansion' },
  { onePoint: "Cradle", threePoint: "Cat's Cradle", deck: 'expansion' },
  { onePoint: "Crate", threePoint: "Training Crate", deck: 'expansion' },
  { onePoint: "Sponge", threePoint: "Kitchen Sponge", deck: 'expansion' },
  { onePoint: "Way", threePoint: "Milky Way", deck: 'expansion' },
  { onePoint: "Peach", threePoint: "Peach Cobbler", deck: 'expansion' },
  { onePoint: "Cough", threePoint: "Cough Syrup", deck: 'expansion' },
  { onePoint: "Count", threePoint: "Countdown", deck: 'expansion' },
  { onePoint: "Corner", threePoint: "Corner Office", deck: 'expansion' },
  { onePoint: "Badge", threePoint: "Sheriff's Badge", deck: 'expansion' },
  { onePoint: "Contest", threePoint: "Costume Contest", deck: 'expansion' },
  { onePoint: "Hermit", threePoint: "Hermit Crab", deck: 'expansion' },
  { onePoint: "Artist", threePoint: "Con Artist", deck: 'expansion' },
  { onePoint: "Coil", threePoint: "Tesla Coil", deck: 'expansion' },
  { onePoint: "Choir", threePoint: "Chapel Choir", deck: 'expansion' },
  { onePoint: "Copy", threePoint: "Copycat", deck: 'expansion' },
  { onePoint: "Collar", threePoint: "Dog Collar", deck: 'expansion' },
  { onePoint: "Choice", threePoint: "Clear Choice", deck: 'expansion' },
  { onePoint: "Compass", threePoint: "Compass Needle", deck: 'expansion' },
  { onePoint: "Professor", threePoint: "Assistant Professor", deck: 'expansion' },
  { onePoint: "Bonnet", threePoint: "Baby Bonnet", deck: 'expansion' },
  { onePoint: "Buy", threePoint: "Buy Time", deck: 'expansion' },
  { onePoint: "Blender", threePoint: "Makeup Blender", deck: 'expansion' },
  { onePoint: "Birth", threePoint: "Birth Certificate", deck: 'expansion' },
  { onePoint: "Tear", threePoint: "Teardrop", deck: 'expansion' },
  { onePoint: "Barrel", threePoint: "Pickle Barrel", deck: 'expansion' },
  { onePoint: "Ancient", threePoint: "Ancient Artifact", deck: 'expansion' },
  { onePoint: "Chapter", threePoint: "Final Chapter", deck: 'expansion' },
  { onePoint: "Briefcase", threePoint: "Leather Briefcase", deck: 'expansion' },
  { onePoint: "Hall", threePoint: "Study Hall", deck: 'expansion' },
  { onePoint: "King", threePoint: "Kingpin", deck: 'expansion' },
  { onePoint: "Tower", threePoint: "Watchtower", deck: 'expansion' },
  { onePoint: "Heat", threePoint: "Heat Wave", deck: 'expansion' },
  { onePoint: "Idea", threePoint: "Bright Idea", deck: 'expansion' },
  { onePoint: "Hay", threePoint: "Hay Bale", deck: 'expansion' },
  { onePoint: "Key", threePoint: "Key Chain", deck: 'expansion' },
  { onePoint: "Kite", threePoint: "Kite Flying", deck: 'expansion' },
  { onePoint: "Hear", threePoint: "Hearing Aid", deck: 'expansion' },
  { onePoint: "Print", threePoint: "Fingerprint", deck: 'expansion' },
  { onePoint: "Bottom", threePoint: "Bottom Line", deck: 'expansion' },
  { onePoint: "Charge", threePoint: "Service Charge", deck: 'expansion' },
  { onePoint: "Ball", threePoint: "Wrecking Ball", deck: 'expansion' },
  { onePoint: "Comb", threePoint: "Comb-Over", deck: 'expansion' },
  { onePoint: "Depth", threePoint: "Depth Perception", deck: 'expansion' },
  { onePoint: "Design", threePoint: "Interion Design", deck: 'expansion' },
  { onePoint: "Control", threePoint: "Remote Control", deck: 'expansion' },
  { onePoint: "Breath", threePoint: "Breath Mint", deck: 'expansion' },
  { onePoint: "Diary", threePoint: "Dear Diary", deck: 'expansion' },
  { onePoint: "Cellar", threePoint: "Wine Cellar", deck: 'expansion' },
  { onePoint: "Bend", threePoint: "Bend Backwards", deck: 'expansion' },
  { onePoint: "Chemical", threePoint: "Chemical Reaction", deck: 'expansion' },
  { onePoint: "Dart", threePoint: "Blow Dart", deck: 'expansion' },
  { onePoint: "Bin", threePoint: "Recycle Bin", deck: 'expansion' },
  { onePoint: "Chill", threePoint: "Chill Out", deck: 'expansion' },
  { onePoint: "Chest", threePoint: "Chestnut", deck: 'expansion' },
  { onePoint: "Tray", threePoint: "Brownie Tray", deck: 'expansion' },
  { onePoint: "Bitter", threePoint: "Bitter Pill", deck: 'expansion' },
  { onePoint: "Barge", threePoint: "Garbage Barge", deck: 'expansion' },
  { onePoint: "Bell", threePoint: "Cathedral Bell", deck: 'expansion' },
  { onePoint: "Enemy", threePoint: "Mortal Enemy", deck: 'expansion' },
  { onePoint: "Dungeon", threePoint: "Dungeon Crawl", deck: 'expansion' },
  { onePoint: "Air", threePoint: "Airbrush", deck: 'expansion' },
  { onePoint: "Apron", threePoint: "Chef Apron", deck: 'expansion' },
  { onePoint: "Echo", threePoint: "Echo Chamber", deck: 'expansion' },
  { onePoint: "Eclipse", threePoint: "Solar Eclipse", deck: 'expansion' },
  { onePoint: "Antler", threePoint: "Deer Antler", deck: 'expansion' },
  { onePoint: "Duck", threePoint: "Sitting Duck", deck: 'expansion' },
  { onePoint: "Job", threePoint: "Job Hunt", deck: 'expansion' },
  { onePoint: "Back", threePoint: "Backpack", deck: 'expansion' },
  { onePoint: "Ink", threePoint: "Ink Stain", deck: 'expansion' },
  { onePoint: "Alpha", threePoint: "Alpha Dog", deck: 'expansion' },
  { onePoint: "Bed", threePoint: "Bunk Bed", deck: 'expansion' },
  { onePoint: "Armor", threePoint: "Body Armor", deck: 'expansion' },
  { onePoint: "Beaver", threePoint: "Eager Beaver", deck: 'expansion' },
  { onePoint: "Bargain", threePoint: "Bargain Bin", deck: 'expansion' },
  { onePoint: "Chandelier", threePoint: "Crystal Chandelier", deck: 'expansion' },
  { onePoint: "Courage", threePoint: "Liquid Courage", deck: 'expansion' },
  { onePoint: "Costume", threePoint: "Superhero Costume", deck: 'expansion' },
  { onePoint: "Curry", threePoint: "Curry Favor", deck: 'expansion' },
  { onePoint: "Crush", threePoint: "Innocent Crush", deck: 'expansion' },
  { onePoint: "Call", threePoint: "Roll Call", deck: 'expansion' },
  { onePoint: "Art", threePoint: "Art Dealer", deck: 'expansion' },
  { onePoint: "Beetle", threePoint: "Dung Beetle", deck: 'expansion' },
  { onePoint: "Beef", threePoint: "Beef Jerky", deck: 'expansion' },
  { onePoint: "Budget", threePoint: "Balanced Budget", deck: 'expansion' },
  { onePoint: "Bike", threePoint: "Tandem Bike", deck: 'expansion' },
  { onePoint: "Cabinet", threePoint: "Kitchen Cabinet", deck: 'expansion' },
  { onePoint: "Autumn", threePoint: "Autumn Leaves", deck: 'expansion' },
  { onePoint: "Chance", threePoint: "Slim Chance", deck: 'expansion' },
  { onePoint: "Punch", threePoint: "Punch Bowl", deck: 'expansion' },
  { onePoint: "Mug", threePoint: "Ceramic Mug", deck: 'expansion' },
  { onePoint: "Dial", threePoint: "Butt Dial", deck: 'expansion' },
  { onePoint: "Act", threePoint: "Act Out", deck: 'expansion' },
  { onePoint: "Cliff", threePoint: "Cliffhanger", deck: 'expansion' },
  { onePoint: "Crop", threePoint: "Crop Top", deck: 'expansion' },
  { onePoint: "Blossom", threePoint: "Spring Blossom", deck: 'expansion' },
  { onePoint: "Blue", threePoint: "Blueprint", deck: 'expansion' },
  { onePoint: "Cross", threePoint: "Cross Your Mind", deck: 'expansion' },
  { onePoint: "Perfume", threePoint: "Perfume Department", deck: 'expansion' },
  { onePoint: "Captain", threePoint: "Fleet Captain", deck: 'expansion' },
  { onePoint: "Daisy", threePoint: "Upsy-daisy", deck: 'expansion' },
  { onePoint: "Drill", threePoint: "Drill Press", deck: 'expansion' },
  { onePoint: "Drink", threePoint: "Energy Drink", deck: 'expansion' },
  { onePoint: "Cage", threePoint: "Rib Cage", deck: 'expansion' },
  { onePoint: "Country", threePoint: "Countryside", deck: 'expansion' },
  { onePoint: "Drag", threePoint: "Drag Race", deck: 'expansion' },
  { onePoint: "Cycle", threePoint: "Moon Cycle", deck: 'expansion' },
  { onePoint: "Chrome", threePoint: "Chrome Plating", deck: 'expansion' },
  { onePoint: "Champion", threePoint: "Grand Champion", deck: 'expansion' },
  { onePoint: "Mammoth", threePoint: "Woolly Mammoth", deck: 'expansion' },
  { onePoint: "Body", threePoint: "Body Lotion", deck: 'expansion' },
  { onePoint: "Buck", threePoint: "Quick Buck", deck: 'expansion' },
  { onePoint: "Cap", threePoint: "Bottle Cap", deck: 'expansion' },
  { onePoint: "Almond", threePoint: "Almond Croissant", deck: 'expansion' },
  { onePoint: "Drawing", threePoint: "Figure Drawing", deck: 'expansion' },
  { onePoint: "Custom", threePoint: "Custom Build", deck: 'expansion' },
  { onePoint: "Career", threePoint: "Career Coach", deck: 'expansion' },
  { onePoint: "Business", threePoint: "Risky Business", deck: 'expansion' },
  { onePoint: "Dancer", threePoint: "Ballet Dancer", deck: 'expansion' },
  { onePoint: "Album", threePoint: "Photo Album", deck: 'expansion' },
  { onePoint: "Action", threePoint: "Live Action", deck: 'expansion' },
  { onePoint: "Bracelet", threePoint: "Charm Bracelet", deck: 'expansion' },
  { onePoint: "Joy", threePoint: "Joystick", deck: 'expansion' },
  { onePoint: "Cinema", threePoint: "Outdoor Cinema", deck: 'expansion' },
  { onePoint: "Curse", threePoint: "Curse Word", deck: 'expansion' },
  { onePoint: "Ivory", threePoint: "Ivory Tower", deck: 'expansion' },
  { onePoint: "Bullet", threePoint: "Bulletproof", deck: 'expansion' },
  { onePoint: "Burglar", threePoint: "Cat Burglar", deck: 'expansion' },
  { onePoint: "Alley", threePoint: "Alley-Oop", deck: 'expansion' },
  { onePoint: "Comic", threePoint: "Comic Strip", deck: 'expansion' },
  { onePoint: "Court", threePoint: "Courtyard", deck: 'expansion' },
  { onePoint: "Crowd", threePoint: "Crowdfunding", deck: 'expansion' },
  { onePoint: "Global", threePoint: "Global Economics", deck: 'expansion' },
  { onePoint: "Dagger", threePoint: "Throwing Dagger", deck: 'expansion' },
  { onePoint: "Cherry", threePoint: "Cherry Blossom", deck: 'expansion' },
  { onePoint: "Baggage", threePoint: "Baggage Claim", deck: 'expansion' },
  { onePoint: "Axis", threePoint: "Polar Axis", deck: 'expansion' },
  { onePoint: "Guardian", threePoint: "Guardian Angel", deck: 'expansion' },
  { onePoint: "Bob", threePoint: "Bobcat", deck: 'expansion' },
  { onePoint: "Clay", threePoint: "Clay Mask", deck: 'expansion' },
  { onePoint: "Cell", threePoint: "Cell Division", deck: 'expansion' },
  { onePoint: "Clothes", threePoint: "Clothesline", deck: 'expansion' },
  { onePoint: "Snack", threePoint: "Crunchy Snack", deck: 'expansion' },
  { onePoint: "Cucumber", threePoint: "Cucumber Water", deck: 'expansion' },
  { onePoint: "Storage", threePoint: "Storage unit", deck: 'expansion' },
  { onePoint: "Snail", threePoint: "Snail Mail", deck: 'expansion' },
  { onePoint: "Boom", threePoint: "Sonic Boom", deck: 'expansion' },
  { onePoint: "Everything", threePoint: "Everything Bagel", deck: 'expansion' },
  { onePoint: "Fiber", threePoint: "Fiber Optics", deck: 'expansion' },
  { onePoint: "Holiday", threePoint: "National Holiday", deck: 'expansion' },
  { onePoint: "Scar", threePoint: "Scar Tissue", deck: 'expansion' },
  { onePoint: "Cloud", threePoint: "Cloud Nine", deck: 'expansion' },
  { onePoint: "Brake", threePoint: "Brake Pad", deck: 'expansion' },
  { onePoint: "Church", threePoint: "Church Bench", deck: 'expansion' },
  { onePoint: "Comedy", threePoint: "Stand-Up Comedy", deck: 'expansion' },
  { onePoint: "Tar", threePoint: "Tar Pit", deck: 'expansion' },
  { onePoint: "Page", threePoint: "Front page", deck: 'expansion' },
  { onePoint: "Willow", threePoint: "Weeping Willow", deck: 'expansion' },
  { onePoint: "Tax", threePoint: "Tax Refund", deck: 'expansion' },
  { onePoint: "Husband", threePoint: "Supportive Husband", deck: 'expansion' },
  { onePoint: "Fashion", threePoint: "Fashion Icon", deck: 'expansion' },
  { onePoint: "Affair", threePoint: "Public Affair", deck: 'expansion' },
  { onePoint: "Field", threePoint: "Force Field", deck: 'expansion' },
  { onePoint: "Work", threePoint: "Workout", deck: 'expansion' },
  { onePoint: "Skull", threePoint: "Crystal Skull", deck: 'expansion' },
  { onePoint: "Mole", threePoint: "Holy Moley", deck: 'expansion' },
  { onePoint: "Box", threePoint: "Music Box", deck: 'expansion' },
  { onePoint: "Eye", threePoint: "Bullseye", deck: 'expansion' },
  { onePoint: "Wind", threePoint: "Wind Chime", deck: 'expansion' },
  { onePoint: "Cereal", threePoint: "Cereal Box", deck: 'expansion' },
  { onePoint: "Cousin", threePoint: "Second Cousin", deck: 'expansion' },
  { onePoint: "Hound", threePoint: "Bloodhound", deck: 'expansion' },
  { onePoint: "Pyramid", threePoint: "Pyramid Scheme", deck: 'expansion' },
  { onePoint: "Prize", threePoint: "Nobel Prize", deck: 'expansion' },
  { onePoint: "Song", threePoint: "Songbird", deck: 'expansion' },
  { onePoint: "City", threePoint: "City Hall", deck: 'expansion' },
  { onePoint: "Ticket", threePoint: "Return Ticket", deck: 'expansion' },
  { onePoint: "Stress", threePoint: "Stress Management", deck: 'expansion' },
  { onePoint: "Heavy", threePoint: "Heavy Burden", deck: 'expansion' },
  { onePoint: "Chalk", threePoint: "Chalkboard", deck: 'expansion' },
  { onePoint: "Math", threePoint: "Math Problem", deck: 'expansion' },
]
